#!/usr/bin/env python3
"""Generate main/sp_spend_vectors.h for the kisstest silent-payments suite.

Offline tool (neither vendored nor run in CI). Covers the RECEIVE side that
gen_vectors.py does not: Stage B scan-key export (BIP-392 sp(spscan) descriptor)
and Stage C spend-from-received (BIP-376 PSBT_IN_SP_TWEAK / _SPEND_BIP32_DERIVATION).

  --embit  path to the SP-capable embit fork's src/ directory, commit cf085f8
           (the submodule of selfcustody/krux PR #870: vendor/embit/src)

Everything the C tests assert flows from here and is self-checked against embit
before it is written, so the kisstest cross-checks a second implementation.

Usage:
  python3 tools/sp_fixtures/gen_spend_vectors.py --embit /path/embit/src
"""

import argparse
import base64
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / "main" / "sp_spend_vectors.h"

# Same dev seed the whole suite (and kiss_crypto selftest) is anchored to.
TEST_MNEMONIC = (
    "abandon abandon abandon abandon abandon abandon abandon abandon "
    "abandon abandon abandon about"
)
COIN = 1  # testnet, matching the send-side fixtures


def chex(b):
    return ", ".join("0x%02x" % x for x in b)


def carr(name, b):
    return "static const uint8_t %s[%d] = { %s };\n" % (name, len(b), chex(b))


def cstr(name, s):
    return 'static const char %s[] = "%s";\n' % (name, s)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--embit", required=True, help="embit fork src/ (commit cf085f8)")
    args = ap.parse_args()
    sys.path.insert(0, str(Path(args.embit).resolve()))

    from embit import bip39, bip32, ec
    from embit.descriptor.sp import SPScanKey
    from embit.descriptor.arguments import KeyOrigin
    from embit.bip32 import parse_path
    from embit.psbt import DerivationPath
    from embit.silent_payments import SilentPaymentsPSBT as PSBT
    from embit.silent_payments.psbt import SPInputScope, SPOutputScope
    from embit.script import Script, p2wpkh
    from embit.transaction import TransactionOutput, SIGHASH
    from embit.hashes import tagged_hash
    from embit.util import secp256k1

    root = bip32.HDKey.from_seed(bip39.mnemonic_to_seed(TEST_MNEMONIC))
    fp = root.my_fingerprint

    def sp_keys(coin):
        scan_priv = root.derive("m/352h/%dh/0h/1h/0" % coin).key
        spend_priv = root.derive("m/352h/%dh/0h/0h/0" % coin).key
        return scan_priv, spend_priv, spend_priv.get_public_key()

    lines = [
        "// Auto-generated by tools/sp_fixtures/gen_spend_vectors.py from the embit\n"
        "// SP fork (commit cf085f8). Do not edit by hand. Stage B (sp(spscan) export)\n"
        "// + Stage C (BIP-376 spend) reference values, cross-checked against embit.\n"
        "#pragma once\n#include <stdint.h>\n\n",
    ]

    # ---- Stage B: sp(spscan) / sp(tspscan) watch-only export ----
    for coin, net, tag in ((0, "main", "MAIN"), (1, "test", "TEST")):
        scan_priv, spend_priv, spend_pub = sp_keys(coin)
        origin = KeyOrigin(fp, parse_path("m/352h/%dh/0h" % coin))
        spscan = SPScanKey(scan_priv, spend_pub, origin=origin, network=net)
        desc = "sp(%s)" % str(spscan)
        lines.append("// %s scan-key export (BIP-392 sp(spscan) descriptor)\n" % net)
        lines.append(cstr("SPV_SPSCAN_%s" % tag, desc))
    lines.append("\n")

    # ---- Stage C: BIP-376 spend fixtures (testnet) ----
    scan_priv, spend_priv, spend_pub = sp_keys(COIN)

    def find_tweak(parity):
        for b in range(1, 256):
            t = bytes([b] * 32)
            if spend_priv.sp_spend_tweak(t).sec()[0] == parity:
                return t
        raise AssertionError("no tweak with parity %02x" % parity)

    def build_spend(tweak, output_xonly=None):
        if output_xonly is None:
            output_xonly = spend_priv.sp_spend_tweak(tweak).xonly()
        inp = SPInputScope()
        inp.txid = bytes([0xCD] * 32)
        inp.vout = 0
        inp.sequence = 0xFFFFFFFE
        inp.witness_utxo = TransactionOutput(
            value=100_000, script_pubkey=Script(b"\x51\x20" + output_xonly))
        inp.sp_tweak = tweak
        inp.sp_spend_bip32_derivations[spend_pub.sec()] = DerivationPath(
            fp, parse_path("m/352h/%dh/0h/0h/0" % COIN))
        psbt = PSBT.create_v2()
        psbt.add_input(inp)
        out = SPOutputScope()
        out.value = 95_000
        out.script_pubkey = p2wpkh(root.derive("m/84h/%dh/0h/1/0" % COIN).get_public_key())
        psbt.add_output(out)
        psbt.tx_modifiable_flags = 0
        return psbt, output_xonly

    def b64(psbt):
        return base64.b64encode(psbt.serialize()).decode()

    def emit_spend(prefix, tweak, output_xonly=None, expect_sign=True):
        psbt, outkey = build_spend(tweak, output_xonly)
        sighash = psbt.sighash(0, sighash=SIGHASH.DEFAULT)
        # embit self-check: signs iff the tweak reproduces the on-chain key
        signer, _ = build_spend(tweak, output_xonly)
        n = signer._sign_sp_spends(root)
        if expect_sign:
            sig = signer.inputs[0].taproot_key_sig
            pub = ec.PublicKey.from_xonly(outkey)
            assert n == 1 and pub.schnorr_verify(ec.SchnorrSig(sig), sighash), \
                "%s: embit failed to sign/verify" % prefix
        else:
            assert n == 0, "%s: embit unexpectedly signed a foreign tweak" % prefix
        lines.append(cstr("SPV_%s_B64" % prefix, b64(psbt)))
        lines.append(carr("SPV_%s_TWEAK" % prefix, tweak))
        lines.append(carr("SPV_%s_OUTKEY" % prefix, outkey))
        lines.append(carr("SPV_%s_SIGHASH" % prefix, sighash))
        lines.append("\n")

    lines.append("// BIP-376 spend: tweak whose (b_spend + t) has even Y\n")
    emit_spend("SPEND_EVEN", find_tweak(0x02))
    lines.append("// BIP-376 spend: tweak whose (b_spend + t) has odd Y (negation path)\n")
    emit_spend("SPEND_ODD", find_tweak(0x03))
    lines.append("// BIP-376 spend: tweak in the PSBT does NOT reproduce the on-chain\n"
                 "// P2TR key -> the signer MUST refuse (anti-theft, BIP-376 MUST-fail)\n")
    onchain = spend_priv.sp_spend_tweak(find_tweak(0x02)).xonly()
    emit_spend("SPEND_FOREIGN", bytes([0x77] * 32), output_xonly=onchain, expect_sign=False)

    # ---- change/self detection (BIP0352/Label) ----
    lines.append("// change/self detection: expected spend key for a labeled SP output\n"
                 "// = spend_pub + hash_BIP0352/Label(scan_priv || ser32(m))*G; label 0 = change\n")
    lines.append(carr("SPV_LABEL_SCAN_PRIV", scan_priv.secret))
    lines.append(carr("SPV_LABEL_SPEND_PUB", spend_pub.sec()))

    def label_spend(m):
        tw = tagged_hash("BIP0352/Label", scan_priv.secret + m.to_bytes(4, "big"))
        P = ec.PublicKey(secp256k1.ec_pubkey_add(
            secp256k1.ec_pubkey_parse(spend_pub.sec()), tw))
        return P.sec()

    lines.append(carr("SPV_LABEL0_SPEND", label_spend(0)))   # change
    lines.append("#define SPV_LABEL5 5u\n")
    lines.append(carr("SPV_LABEL5_SPEND", label_spend(5)))   # self (labeled)

    OUT.write_text("".join(lines))
    print("wrote", OUT)


if __name__ == "__main__":
    main()
