#!/usr/bin/env python3
"""Generate KISS's independent BIP461 draft fixtures (not official BIP vectors).

Run: python3 tools/sign_fixtures/gen_bip461_vectors.py > sim/bip461_vectors.h
Uses the pure-Python reference, never libwally/libsecp256k1.
"""
from gen_boot_vectors import N, KEY, MSG, _xb, ecdsa_sign_grind

print("// Generated by tools/sign_fixtures/gen_bip461_vectors.py; test keys only.")
print("// BIP461 draft reviewed 2026-09-17. Independent KISS fixtures.")
print("static const struct { const char *key, *msg, *sig; } bip461_vectors[] = {")
for key, msg in [(KEY, MSG)] + [(_xb(k), _xb(m)) for k in (1, N - 1)
                              for m in (0, 1, N - 1, N, N + 1, 2**256 - 1)]:
    sig, counter = ecdsa_sign_grind(key, msg)
    print(f'    {{"{key.hex()}", "{msg.hex()}",\n     "{sig.hex()}"}}, // grind {counter}')
print("};")
