// GENERATED by assets/generators/flag_imgs.py - do not hand-edit
// Twemoji flags, CC-BY 4.0 (assets/twemoji/README.md)
#pragma once
#include "lvgl.h"

// indexed by the i18n.h language enum; NULL = no flag
extern const lv_image_dsc_t *const img_lang_flags[22];
