#pragma once
#include "lvgl.h"
extern lv_image_dsc_t img_wallet;

/* ---- generated by tools/bake_art.py -- do not edit below ---- */
#include "kiss_art.h"
extern const art_entry_t kiss_img_art[];
extern const int kiss_img_art_n;
