// Wallet i18n fonts, generated by tools/fonts/gen_fonts.sh. bpp4.
//   font_kiss_lat14/28  Montserrat: ASCII + Latin-Ext + Vietnamese + Cyrillic
//                       + the LV_SYMBOL_* icons (FontAwesome PUA)
//   font_kiss_{ja,ko,zh}14/28  Source Han Sans subsets: exactly the glyphs the
//                       matching i18n/*.json uses
// The generated files retain a broad fallback chain for standalone use.
// wallet_theme.c builds locale-specific composites so shared Han codepoints
// resolve through JP for Japanese and SC for Simplified Chinese.
// NEVER render text with glyphs outside these fonts: a fully-missing-glyph
// label hard-hangs the LVGL renderer (tools/gen_i18n.py enforces coverage).
#pragma once
#include "lvgl.h"

LV_FONT_DECLARE(font_kiss_lat14);
LV_FONT_DECLARE(font_kiss_lat23);   // wallet-home tile titles; CJK subset = tile words only
LV_FONT_DECLARE(font_kiss_lat28);
// Latin/Cyrillic only -- no ja/ko/zh sibling exists at 34. See wt_font34().
LV_FONT_DECLARE(font_kiss_lat34);
LV_FONT_DECLARE(font_kiss_ja23);
LV_FONT_DECLARE(font_kiss_ko23);
LV_FONT_DECLARE(font_kiss_zh23);
LV_FONT_DECLARE(font_kiss_ja14);
LV_FONT_DECLARE(font_kiss_ja28);
LV_FONT_DECLARE(font_kiss_ko14);
LV_FONT_DECLARE(font_kiss_ko28);
LV_FONT_DECLARE(font_kiss_zh14);
LV_FONT_DECLARE(font_kiss_zh28);
