#pragma once
#include "lvgl.h"
extern lv_image_dsc_t img_menu;
extern lv_image_dsc_t img_saver;

/* ---- generated by tools/bake_art.py -- do not edit below ---- */
#include "wallet_art.h"
extern const art_entry_t menu_img_art[];
extern const int menu_img_art_n;
