#pragma once
#include "lvgl.h"
#define LOGO_LT_N 11
#define MENU_FRUIT_N 4
extern lv_image_dsc_t img_logo_lt[LOGO_LT_N];
extern const int16_t logo_lt_x[LOGO_LT_N], logo_lt_y[LOGO_LT_N];
extern lv_image_dsc_t img_menu_fruit[MENU_FRUIT_N];
extern const int16_t menu_fruit_x[MENU_FRUIT_N], menu_fruit_y[MENU_FRUIT_N];

/* ---- generated by tools/bake_art.py -- do not edit below ---- */
#include "wallet_art.h"
extern const art_entry_t menu_logo_art[];
extern const int menu_logo_art_n;
