// GENERATED by sim/pq_tool.c -- do not edit.
//
// The SLH-DSA-SHA2-128s public key this firmware checks update images against.
// All zeroes means NO KEY, and a build with no key refuses to install anything
// rather than installing whatever it is handed -- see kiss_pqsig_available().
//
// The SECRET half never enters this repository. Public keys do: docs/installer/
// kiss_signer.pub is here for the same reason.
#pragma once
#include <stdint.h>

static const uint8_t PQ_RELEASE_PUBKEY[32] = {
    0x53, 0xCB, 0x97, 0xD6, 0x5F, 0x7E, 0xF4, 0x59, 0xD3, 0xE3, 0xF6, 0x17,
    0xD5, 0xF6, 0xEF, 0x01, 0x41, 0x81, 0x75, 0xE9, 0x15, 0xFC, 0x91, 0x84,
    0x8F, 0x08, 0x67, 0x70, 0x9C, 0xF4, 0x75, 0x94,
};
