#pragma once
#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

extern lv_image_dsc_t img_watermelon;
extern lv_image_dsc_t img_watermelon_half;
extern lv_image_dsc_t img_watermelon_halfr;
extern lv_image_dsc_t img_apple;
extern lv_image_dsc_t img_apple_half;
extern lv_image_dsc_t img_apple_halfr;
extern lv_image_dsc_t img_orange;
extern lv_image_dsc_t img_orange_half;
extern lv_image_dsc_t img_orange_halfr;
extern lv_image_dsc_t img_pineapple;
extern lv_image_dsc_t img_pineapple_half;
extern lv_image_dsc_t img_pineapple_halfr;
extern lv_image_dsc_t img_strawberry;
extern lv_image_dsc_t img_cherries;
extern lv_image_dsc_t img_grapes;
extern lv_image_dsc_t img_bomb;
extern lv_image_dsc_t img_explosion;
extern lv_image_dsc_t img_splat;
extern lv_image_dsc_t img_droplet;
extern lv_image_dsc_t img_heart;
extern lv_image_dsc_t img_heart_empty;

#ifdef __cplusplus
}
#endif

/* ---- generated by tools/bake_art.py -- do not edit below ---- */
#include "kiss_art.h"
extern const art_entry_t sprites_art[];
extern const int sprites_art_n;
