// GENERATED by assets/generators/kiss_mock.py - do not hand-edit
#pragma once
#include "lvgl.h"

#define TILE_LBL_Y 262   // screen y for every strip; x = 50 + i*180
extern const lv_image_dsc_t img_tile_lbls[4];
