// GENERATED by tools/gen_verify_page.py from docs/verify.html - do not hand-edit
// The offline audit checker, written to the card as WPROOF_PAGE_NAME
// beside the frame it checks. See docs/specs/prove-it.md.
#pragma once
#include <stdint.h>
#include <stddef.h>

extern const uint8_t verify_page_html[];
extern const size_t verify_page_html_len;
