#pragma once
#include "lvgl.h"
extern lv_image_dsc_t img_wallet;

/* ---- generated by tools/bake_art.py -- do not edit below ---- */
#include "wallet_art.h"
extern const art_entry_t wallet_img_art[];
extern const int wallet_img_art_n;
