#!/usr/bin/env python3
"""Language-picker flag sprites from the vendored Twemoji flag PNGs
(assets/twemoji/flags/, CC-BY 4.0 - see assets/twemoji/README.md).

Emits main/flag_imgs.c/.h: one RGB565A8 sprite per language that HAS a flag
(English deliberately has none - a language is not a country), plus a lookup
table img_lang_flags[] in main/i18n.h enum order (NULL = no flag).

Run from anywhere; writes into main/ and previews to /tmp/flags_mock.png.
"""
import os
import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "twemoji", "flags")
OUT = os.path.join(os.path.dirname(ROOT), "main")
FLAG_H = 22   # target height inside the 46px picker pills

# i18n.h enum order; None = no flag (English)
LANGS = [
    ("en", None),
    ("de", "1f1e9-1f1ea"),
    ("es", "1f1f2-1f1fd"),
    ("fr", "1f1eb-1f1f7"),
    ("it", "1f1ee-1f1f9"),
    ("ja", "1f1ef-1f1f5"),
    ("ko", "1f1f0-1f1f7"),
    ("nl", "1f1f3-1f1f1"),
    ("pl", "1f1f5-1f1f1"),
    ("pt", "1f1e7-1f1f7"),
    ("ru", "1f1f7-1f1fa"),
    ("tr", "1f1f9-1f1f7"),
    ("vi", "1f1fb-1f1f3"),
    ("zh", "1f1e8-1f1f3"),
    ("es_es", "1f1ea-1f1f8"),
    ("pt_pt", "1f1f5-1f1f9"),
    ("nb", "1f1f3-1f1f4"),
    ("sv", "1f1f8-1f1ea"),
    ("da", "1f1e9-1f1f0"),
    ("cs", "1f1e8-1f1ff"),
    ("hr", "1f1ed-1f1f7"),
    ("hu", "1f1ed-1f1fa"),
]

c_lines = ['#include "lvgl.h"', ""]
entries = []
prev_tiles = []
for ident, code in LANGS:
    if code is None:
        entries.append(("NULL", ident))
        continue
    im = Image.open(os.path.join(SRC, code + ".png")).convert("RGBA")
    im = im.crop(im.getbbox())                      # drop transparent margins
    w = max(1, round(im.width * FLAG_H / im.height))
    im = im.resize((w, FLAG_H), Image.LANCZOS)
    prev_tiles.append((ident, im))

    a = np.array(im)
    r16 = a[..., 0].astype(np.uint16)
    g16 = a[..., 1].astype(np.uint16)
    b16 = a[..., 2].astype(np.uint16)
    al = a[..., 3].astype(np.uint8)
    v16 = (r16 >> 3) << 11 | (g16 >> 2) << 5 | (b16 >> 3)
    data = np.concatenate([
        np.dstack([(v16 & 0xFF).astype(np.uint8),
                   (v16 >> 8).astype(np.uint8)]).reshape(-1),
        al.reshape(-1)])
    c_lines.append("static const uint8_t flag_%s_map[] = {%s};" %
                   (ident, ",".join(str(int(x)) for x in data)))
    c_lines.append("static const lv_image_dsc_t flag_%s = {" % ident)
    c_lines.append("  .header = {.magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565A8,")
    c_lines.append("             .flags = 0, .w = %d, .h = %d, .stride = %d}," % (w, FLAG_H, w * 2))
    c_lines.append("  .data_size = sizeof(flag_%s_map), .data = flag_%s_map};" % (ident, ident))
    entries.append(("&flag_%s" % ident, ident))

c_lines.append("")
c_lines.append("// i18n.h enum order; NULL = no flag for that language (en)")
c_lines.append("const lv_image_dsc_t *const img_lang_flags[%d] = {" % len(LANGS))
for ref, ident in entries:
    c_lines.append("  %s,   // %s" % (ref, ident))
c_lines.append("};")

hdr = ("// GENERATED by assets/generators/flag_imgs.py - do not hand-edit\n"
       "// Twemoji flags, CC-BY 4.0 (assets/twemoji/README.md)\n")
with open(os.path.join(OUT, "flag_imgs.c"), "w") as f:
    f.write(hdr + "\n".join(c_lines) + "\n")
with open(os.path.join(OUT, "flag_imgs.h"), "w") as f:
    f.write(hdr + "#pragma once\n#include \"lvgl.h\"\n\n"
            "// indexed by the i18n.h language enum; NULL = no flag\n"
            "extern const lv_image_dsc_t *const img_lang_flags[%d];\n" % len(LANGS))

# preview strip (hard rule: eyeball generated art before flashing)
pw = sum(t.width + 12 for _, t in prev_tiles) + 12
prev = Image.new("RGBA", (pw, FLAG_H + 24), (16, 20, 29, 255))
x = 12
for ident, t in prev_tiles:
    prev.paste(t, (x, 12), t)
    x += t.width + 12
prev.convert("RGB").save("/tmp/flags_mock.png")
print("wrote main/flag_imgs.c/.h (%d flags) + /tmp/flags_mock.png" % len(prev_tiles))
