#!/usr/bin/env python3
"""Generate the tiny tiled RGB565 backdrop used during gameplay."""
from pathlib import Path


TILE = 46
BASE = (0x00, 0x08, 0x0F)
GRID = (0x29, 0x30, 0x39)
ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "main"


def rgb565(rgb):
    r, g, b = rgb
    return (r >> 3) << 11 | (g >> 2) << 5 | (b >> 3)


data = bytearray()
for y in range(TILE):
    for x in range(TILE):
        value = rgb565(GRID if x == 0 or y == 0 else BASE)
        data.extend((value & 0xFF, value >> 8))

rows = []
for offset in range(0, len(data), 24):
    rows.append("    " + ",".join(map(str, data[offset:offset + 24])) + ",")

(OUT / "game_bg.c").write_text(
    "// GENERATED by assets/generators/game_bg.py - do not hand-edit\n"
    '#include "game_bg.h"\n\n'
    "static const uint8_t game_bg_map[] = {\n"
    + "\n".join(rows)
    + "\n};\n\n"
    "const lv_image_dsc_t img_game_bg = {\n"
    "    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,\n"
    f"                .flags = 0, .w = {TILE}, .h = {TILE}, .stride = {TILE * 2} }},\n"
    "    .data_size = sizeof(game_bg_map), .data = game_bg_map,\n"
    "};\n"
)

(OUT / "game_bg.h").write_text(
    "// GENERATED by assets/generators/game_bg.py - do not hand-edit\n"
    "#pragma once\n"
    '#include "lvgl.h"\n\n'
    "extern const lv_image_dsc_t img_game_bg;\n"
)

print(f"wrote main/game_bg.c/.h ({TILE}x{TILE} RGB565, {len(data)} bytes)")
