#!/usr/bin/env python3
"""Compress the baked LVGL art in main/*.c from raw pixels to RLE.

Why: the art is 52% of the app binary and 1.65x everything that executes.
Four of the images are 800x480 RGB565 backdrops at exactly 768,000 bytes each,
sitting uncompressed in .rodata. The partition is 94% full and flash encryption
still has to land on top of that.

What this does, per file:

  * `static const uint8_t NAME[] = {...}`  ->  `static const uint8_t NAME_rle[]`
  * every descriptor that pointed at NAME gets `.data = NULL, .data_size = 0`
  * the descriptor loses `const`, because wallet_art.c fills `.data` in at boot
  * an `art_entry_t` table is appended, naming every descriptor in the file

The pixels come back at boot in art_unpack_all() (main/wallet_art.c), into
PSRAM. After that LVGL sees ordinary uncompressed images exactly as before --
no LVGL config is touched, no decoder is wired, nothing decompresses twice.

The format is LVGL's own RLE (managed_components/lvgl__lvgl/src/libs/rle/
lv_rle.c) so the bytes stay recognisable to anyone who knows LVGL, but the
decoder we run is ours and is 40 auditable lines. A control byte with the high
bit set copies N blocks literally; with it clear it repeats the next block N
times; N is at most 127 either way.

Nothing is written unless every map in the file round trips byte for byte
first. The uncompressed originals stay recoverable from git.

Usage:
    python3 tools/bake_art.py            # bake, in place
    python3 tools/bake_art.py --check    # report only, touch nothing
"""

import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# The five files carrying baked pixels. flag_imgs.c is deliberately not here:
# it is 40 KB total, which is noise against 4 MB, and every file in this list
# is a file whose descriptors stop being const.
FILES = [
    "main/menu_img.c",
    "main/gameover_img.c",
    "main/wallet_img.c",
    "main/sprites.c",
    "main/menu_logo.c",
]

HEADERS = [
    "main/menu_img.h",
    "main/gameover_img.h",
    "main/wallet_img.h",
    "main/sprites.h",
    "main/menu_logo.h",
]

MARK = "/* ---- generated by tools/bake_art.py -- do not edit below ---- */"


# ---------------------------------------------------------------- codec ----
def rle_compress(data, blk):
    """LVGL-compatible RLE. Returns None if `data` is not a whole number of
    blocks, since the decoder walks in block steps and would run off the end."""
    if len(data) % blk:
        return None
    n = len(data) // blk
    blocks = [data[i * blk:(i + 1) * blk] for i in range(n)]
    out = bytearray()
    i = 0
    while i < n:
        # How far does a run of identical blocks reach? 127 is the ceiling the
        # control byte can express.
        j = i
        while j + 1 < n and blocks[j + 1] == blocks[i] and (j - i + 1) < 127:
            j += 1
        run = j - i + 1
        if run >= 2:
            # A repeat costs 1 + blk for any length; a literal of the same
            # length costs 1 + run*blk. So repeats win from two blocks up.
            out.append(run)
            out += blocks[i]
            i = j + 1
            continue
        # Otherwise gather literals until a run starts or the count fills.
        lit = []
        k = i
        while k < n and len(lit) < 127:
            if k + 1 < n and blocks[k + 1] == blocks[k]:
                break
            lit.append(blocks[k])
            k += 1
        if not lit:                       # k == i and a run starts at i
            lit = [blocks[i]]
            k = i + 1
        out.append(0x80 | len(lit))
        for b in lit:
            out += b
        i = k
    return bytes(out)


def rle_decompress(inp, out_len, blk):
    """Byte for byte what main/wallet_art.c does, so the round trip below
    tests the shipped decoder's contract and not just this file's arithmetic."""
    out = bytearray()
    i = 0
    while i < len(inp):
        ctrl = inp[i]
        i += 1
        if ctrl & 0x80:
            nbytes = blk * (ctrl & 0x7F)
            if i + nbytes > len(inp):
                return None
            out += inp[i:i + nbytes]
            i += nbytes
        else:
            if i + blk > len(inp):
                return None
            out += inp[i:i + blk] * ctrl
            i += blk
        if len(out) > out_len:
            return None
    return bytes(out)


def best_blk(data, cf):
    """RGB565 wants 2-byte blocks; the A8 plane of an RGB565A8 image wants 1.
    Rather than split the planes -- which would mean two entries and two
    buffers per sprite -- just encode both ways and keep the smaller. The
    chosen size travels in the table, so the decoder never has to guess."""
    best = None
    for blk in (1, 2, 4):
        if blk == 4 and "8888" not in cf:
            continue
        enc = rle_compress(data, blk)
        if enc is None:
            continue
        if best is None or len(enc) < len(best[1]):
            best = (blk, enc)
    return best


# --------------------------------------------------------------- parsing ---
MAP_RE = re.compile(r'static const uint8_t (\w+)\[\]\s*=\s*\{(.*?)\};', re.S)
NUM_RE = re.compile(r'\b(\d{1,3})\b')
DSC_RE = re.compile(
    r'\bconst\s+lv_image_dsc_t\s+(\w+)\s*(\[[^\]]*\])?\s*=\s*\{', re.S)


def brace_span(txt, open_idx):
    """Index just past the `}` matching the `{` at open_idx."""
    depth = 0
    for i in range(open_idx, len(txt)):
        if txt[i] == '{':
            depth += 1
        elif txt[i] == '}':
            depth -= 1
            if depth == 0:
                return i + 1
    raise ValueError("unbalanced braces")


def parse(txt):
    """-> (maps, descriptors). A descriptor is (address_expr, map_name, cf)."""
    maps = {}
    for m in MAP_RE.finditer(txt):
        maps[m.group(1)] = bytes(int(x) & 0xFF for x in NUM_RE.findall(m.group(2)))

    dscs = []
    for m in DSC_RE.finditer(txt):
        name, sub = m.group(1), m.group(2)
        body = txt[m.end() - 1:brace_span(txt, m.end() - 1)]
        # `.cf` and `.data` alternate one pair per element, in source order.
        cfs = re.findall(r'\.cf\s*=\s*(LV_COLOR_FORMAT_\w+)', body)
        datas = re.findall(r'\.data\s*=\s*(\w+)\b', body)
        if len(cfs) != len(datas):
            raise ValueError(f"{name}: {len(cfs)} cf but {len(datas)} data")
        for i, (cf, dat) in enumerate(zip(cfs, datas)):
            if dat not in maps:
                continue                  # already baked, or points elsewhere
            addr = f"&{name}[{i}]" if sub else f"&{name}"
            dscs.append((addr, dat, cf))
    return maps, dscs


# -------------------------------------------------------------- emitting ---
def c_bytes(data, indent="  "):
    lines = []
    for i in range(0, len(data), 24):
        lines.append(indent + ",".join(str(b) for b in data[i:i + 24]) + ",")
    if lines:
        lines[-1] = lines[-1].rstrip(",")
    return "\n".join(lines)


def bake_file(path, check):
    rel = os.path.relpath(path, REPO)
    txt = open(path, encoding="utf-8", errors="surrogateescape").read()
    if MARK in txt:
        print(f"  {rel}: already baked, skipped")
        return None

    maps, dscs = parse(txt)
    if not maps:
        print(f"  {rel}: no raw maps found, skipped")
        return None

    used = {d[1] for d in dscs}
    orphan = set(maps) - used
    if orphan:
        # A map nothing points at would be silently dropped from the table and
        # then silently dropped by the linker. Say so rather than shrink by
        # accident.
        raise ValueError(f"{rel}: maps with no descriptor: {sorted(orphan)}")

    cf_of = {d[1]: d[2] for d in dscs}
    enc, raw_tot, enc_tot = {}, 0, 0
    for name, data in maps.items():
        got = best_blk(data, cf_of[name])
        if got is None:
            raise ValueError(f"{rel}: {name} ({len(data)} B) will not block")
        blk, payload = got
        back = rle_decompress(payload, len(data), blk)
        if back != data:
            raise ValueError(f"{rel}: {name} does NOT round trip -- not written")
        enc[name] = (blk, payload, len(data))
        raw_tot += len(data)
        enc_tot += len(payload)

    pct = enc_tot * 100.0 / raw_tot
    print(f"  {rel}: {len(maps)} maps  {raw_tot:>9,} -> {enc_tot:>8,} B "
          f"({pct:4.1f}%)  all round trip OK")
    if check:
        return raw_tot - enc_tot

    out = txt
    # 1. maps -> compressed maps
    for name, (blk, payload, raw_len) in enc.items():
        old = MAP_RE.search(out)
        pat = re.compile(r'static const uint8_t %s\[\]\s*=\s*\{.*?\};' % re.escape(name), re.S)
        new = ("static const uint8_t %s_rle[] = {\n%s\n};"
               % (name, c_bytes(payload)))
        out, n = pat.subn(lambda _m: new, out, count=1)
        if n != 1:
            raise ValueError(f"{rel}: could not replace map {name}")

    # 2. descriptors: drop const, empty the data fields
    out = re.sub(r'\bconst\s+(lv_image_dsc_t\s+\w+\s*(\[[^\]]*\])?\s*=)', r'\1', out)
    for name in enc:
        out = re.sub(r'\.data_size\s*=\s*sizeof\(\s*%s\s*\)' % re.escape(name),
                     '.data_size = 0', out)
        out = re.sub(r'\.data_size\s*=\s*sizeof\s+%s\b' % re.escape(name),
                     '.data_size = 0', out)
        out = re.sub(r'\.data\s*=\s*%s\b' % re.escape(name), '.data = NULL', out)

    # 3. the table this file contributes to art_unpack_all
    stem = os.path.splitext(os.path.basename(path))[0]
    rows = []
    for addr, name, _cf in dscs:
        blk, payload, raw_len = enc[name]
        rows.append("  { %s, %s_rle, sizeof %s_rle, %d, %d },"
                    % (addr, name, name, raw_len, blk))
    table = "\n".join([
        "",
        MARK,
        '#include "wallet_art.h"',
        "const art_entry_t %s_art[] = {" % stem,
        "\n".join(rows),
        "};",
        "const int %s_art_n = %d;" % (stem, len(rows)),
        "",
    ])
    out = out.rstrip() + "\n" + table

    open(path, "w", encoding="utf-8", errors="surrogateescape").write(out)
    return raw_tot - enc_tot


def bake_header(path, stem, check):
    txt = open(path, encoding="utf-8", errors="surrogateescape").read()
    if MARK in txt:
        return
    if check:
        return
    # The descriptors are filled in at boot, so they are no longer const.
    out = re.sub(r'\bextern\s+const\s+(lv_image_dsc_t)\b', r'extern \1', txt)
    out = out.rstrip() + "\n\n" + "\n".join([
        MARK,
        '#include "wallet_art.h"',
        "extern const art_entry_t %s_art[];" % stem,
        "extern const int %s_art_n;" % stem,
        "",
    ])
    open(path, "w", encoding="utf-8", errors="surrogateescape").write(out)


def main():
    check = "--check" in sys.argv
    print("bake_art: %s" % ("checking (nothing will be written)" if check else "baking"))
    total = 0
    for c, h in zip(FILES, HEADERS):
        cp, hp = os.path.join(REPO, c), os.path.join(REPO, h)
        saved = bake_file(cp, check)
        if saved is None:
            continue
        total += saved
        bake_header(hp, os.path.splitext(os.path.basename(c))[0], check)
    print(f"\nflash saved: {total:,} B ({total / 1048576.0:.2f} MB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
