#!/usr/bin/env python3
"""Do the staged installer artifacts describe the release VERSION names?

docs/installer/ is what the browser installer writes to a device, and it is
generated by tools/make_web_release.sh from a real build. Nothing regenerates
it automatically, so it goes stale the moment VERSION moves and nothing notices
until someone flashes a device from the website and gets firmware the rest of
the documentation does not describe. That happened between beta6 and beta7: the
site served beta6 while the README, the changelog and every screenshot were
beta7, which is the storage release.

The version is hardcoded in four places. This checks all four agree with
VERSION, the same discipline already applied to screenshots by
tools/gen_docs_shots.py --check.

A release carries one image per board. release.json lists them under
"boards", and a release made before that list existed describes the Guition
alone at its top level, which is still read that way. Every board's image has
to exist, hash to what release.json says, be listed with that hash in
SHA256SUMS, and have a manifest that flashes it and nothing else -- and the
top-level fields, which older links and scripts read, have to stay the
Guition's.

Hand editing the version strings does NOT fix a mismatch. The sha256 and size
in release.json describe a specific binary and docs/app.js verifies against
them, so editing the version alone produces a page that fails its own hash
check. The fix is to rerun tools/make_web_release.sh from a release build, or
to pull the install button until you can. See docs/installer/SIGNING.md.

What counts as a failure depends on whether the site is actually offering the
firmware. There are two consistent states and one broken one:

  * install card present, artifacts match VERSION   -> fine
  * install card pulled                             -> fine, nothing is offered
  * install card present, artifacts stale           -> BROKEN, this is the bug

So a stale artifact set is only fatal while docs/index.html still carries the
install button. With the button pulled it is reported and the check passes,
because no one can flash anything from the page. That keeps the tree mergeable
during the window where a release is staged, while making it impossible to put
the button back without regenerating first, which is the mistake worth
preventing.

Exit 0 when the site is consistent, 1 when it would offer a stale binary.
"""

import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
INSTALLER = ROOT / "docs" / "installer"
INDEX = ROOT / "docs" / "index.html"


# The one form a manifest name may take: release.json hands it to the page, and
# the page turns it into a URL, so anything else is refused on both sides.
MANIFEST_RE = re.compile(r"^manifest[\w-]*\.json$")
DIGEST_RE = re.compile(r"\b[0-9a-f]{64}\b")


def release_boards(release: dict) -> list:
    """The boards a release.json describes: its "boards" list, or the Guition
    alone for a release made before that list existed."""
    boards = release.get("boards")
    if boards is None:
        return [{"id": "guition", "manifest": "manifest.json",
                 "browserFirmware": release.get("browserFirmware") or {}}]
    return boards if isinstance(boards, list) else []


def expect_var(board_id: str) -> str:
    """The verify page's variable for a board's hash. The Guition's kept the
    name it had when it was the only one."""
    return "EXPECT" if board_id == "guition" else "EXPECT_" + board_id.upper()


def verify_page_problems(text: str, boards: list) -> list:
    """What docs/verify-release.html bakes, held against the release's boards.

    A board in the release needs its hash, size and file name in the script and
    in its line at the foot of the page. A board the page has a slot for and the
    release does not carry needs that slot empty: left alone it would go on
    passing the previous release's image as a match.
    """
    problems = []
    by_id = {b.get("id"): b for b in boards}
    slots = re.findall(r'<p class="mut expect" data-board="([\w-]+)">(.*?)</p>',
                       text, flags=re.S)
    slot_text = dict(slots)
    for bid, board in by_id.items():
        bf = board.get("browserFirmware") or {}
        name = pathlib.PurePosixPath(bf.get("path", "")).name
        var = expect_var(bid)
        for decl in (f'var {var} = "{bf.get("sha256")}";',
                     f'var {var}_SIZE = {bf.get("size")};',
                     f'var {var}_NAME = "{name}";'):
            if decl not in text:
                problems.append(f"docs/verify-release.html lacks `{decl}` "
                                f"from release.json")
        line = slot_text.get(bid)
        if line is None:
            problems.append(f"docs/verify-release.html has no expected-hash line "
                            f"for board {bid!r}")
        elif bf.get("sha256", "-") not in line or name not in line:
            problems.append(f"docs/verify-release.html's line for board {bid!r} "
                            f"does not show {name} and its hash")
    for bid, line in slots:
        if bid in by_id:
            continue
        var = expect_var(bid)
        if f'var {var} = "";' not in text or DIGEST_RE.search(line):
            problems.append(f"docs/verify-release.html still carries a hash for "
                            f"board {bid!r}, which this release has no image for")
    return problems


def install_button_live() -> bool:
    """Is the page actually offering to flash a device?

    The custom element is what does the flashing, so its presence in real
    markup is the signal. Commented-out markup does not count, which is how the
    button is parked while a release is staged.
    """
    if not INDEX.is_file():
        return False
    return button_is_live(INDEX.read_text())


def button_is_live(html: str) -> bool:
    html = re.sub(r"<!--.*?-->", "", html, flags=re.DOTALL)
    return "<esp-web-install-button" in html


# This gate's whole skip condition is button_is_live: with the button parked
# the page cannot flash anything, so a stale binary beside it is reported and
# the check passes. That makes the comment-stripping regex the most dangerous
# line in the file. If it stopped matching comments the gate would refuse every
# staged release; if it started swallowing real markup the gate would skip
# itself silently and a stale binary could ship behind a live button, which is
# the exact failure between beta6 and beta7 that this file exists for.
#
# So the self test is that regex, in the four shapes docs/index.html has
# actually held it, and the version comparison beside it.
#
# What a commit field may look like. `git describe` output is the shape this
# rejects: it names the newest tag reachable from HEAD, and a release is built
# before it is tagged, so describe always names the PREVIOUS release -- two
# releases back when the branch has not merged main. beta9 shipped saying
# `v0.1.0-beta7-1054-gbdcfa7be`, which reads to anyone comparing the page
# against the device as the wrong firmware entirely.
COMMIT_RE = re.compile(r"^[0-9a-f]{7,40}(-dirty)?$")


def is_commit(rev: str) -> bool:
    return bool(COMMIT_RE.match(rev or ""))


def selftest() -> int:
    bad = 0
    count = 0
    cases = [
        ("real markup is a live button",
         '<esp-web-install-button manifest="m.json"></esp-web-install-button>',
         True),
        ("markup inside a comment is parked",
         '<!-- <esp-web-install-button manifest="m.json"> -->', False),
        ("markup inside a MULTI LINE comment is parked",
         '<!--\n  <esp-web-install-button\n     manifest="m.json">\n-->', False),
        ("a page with no button at all is parked",
         "<p>nothing here</p>", False),
        ("a live button after a closed comment still counts",
         '<!-- parked once -->\n<esp-web-install-button>', True),
    ]
    for name, html, want in cases:
        got = button_is_live(html)
        ok = got == want
        print("  %-52s %s (%s)" % (name, "ok" if ok else "FAILED", got))
        bad += not ok
        count += 1

    # The version rule the manifest is held to: a prefix match, because the
    # generator writes "<version>-<commit>".
    for name, manifest_version, version, want in [
        ("an exact manifest version matches", "0.1.0-beta9", "0.1.0-beta9", True),
        ("a commit suffix still matches",
         "0.1.0-beta9-abc1234", "0.1.0-beta9", True),
        ("a different version does not match",
         "0.1.0-beta8", "0.1.0-beta9", False),
    ]:
        got = manifest_version.startswith(version)
        ok = got == want
        print("  %-52s %s (%s)" % (name, "ok" if ok else "FAILED", got))
        bad += not ok
        count += 1

    for name, rev, want in [
        ("a bare short hash is a commit", "bdcfa7be", True),
        ("a dirty hash is still a commit", "bdcfa7be-dirty", True),
        ("a describe string is NOT", "v0.1.0-beta7-1054-gbdcfa7be", False),
        ("a bare tag is NOT", "v0.1.0-beta9", False),
    ]:
        got = is_commit(rev)
        ok = got == want
        print("  %-52s %s (%s)" % (name, "ok" if ok else "FAILED", got))
        bad += not ok
        count += 1

    # The two shapes of release.json. Reading the old one as "no boards" would
    # make every check below it pass on nothing.
    guition_fw = {"path": "firmware/kiss-signer-1.bin", "offset": 0,
                  "size": 3, "sha256": "a" * 64}
    ws35_fw = {"path": "firmware/kiss-signer-1-ws35.bin", "offset": 0,
               "size": 4, "sha256": "b" * 64}
    for name, release, want in [
        ("a release without a boards list is the Guition",
         {"browserFirmware": guition_fw}, [("guition", "manifest.json")]),
        ("a boards list is read as it stands",
         {"browserFirmware": guition_fw, "boards": [
             {"id": "guition", "manifest": "manifest.json", "browserFirmware": guition_fw},
             {"id": "ws35", "manifest": "manifest-ws35.json", "browserFirmware": ws35_fw}]},
         [("guition", "manifest.json"), ("ws35", "manifest-ws35.json")]),
    ]:
        got = [(b["id"], b["manifest"]) for b in release_boards(release)]
        ok = got == want
        print("  %-52s %s (%s)" % (name, "ok" if ok else "FAILED", got))
        bad += not ok
        count += 1

    # The verify page, in the three states a board's slot can be in.
    def page(ws35_hash, ws35_line):
        return (f'var EXPECT = "{"a" * 64}";\nvar EXPECT_SIZE = 3;\n'
                f'var EXPECT_NAME = "kiss-signer-1.bin";\n'
                f'var EXPECT_WS35 = "{ws35_hash}";\n'
                f'var EXPECT_WS35_SIZE = {4 if ws35_hash else 0};\n'
                f'var EXPECT_WS35_NAME = "{"kiss-signer-1-ws35.bin" if ws35_hash else ""}";\n'
                f'<p class="mut expect" data-board="guition">Guition, '
                f'<span class="mono">kiss-signer-1.bin</span>: {"a" * 64}</p>\n'
                f'<p class="mut expect" data-board="ws35">{ws35_line}</p>\n')
    one = [{"id": "guition", "browserFirmware": guition_fw}]
    two = one + [{"id": "ws35", "browserFirmware": ws35_fw}]
    for name, text, boards, want in [
        ("a page baked for both boards passes",
         page("b" * 64, "Waveshare, kiss-signer-1-ws35.bin: " + "b" * 64), two, 0),
        ("an absent board with an empty slot passes",
         page("", "Waveshare: no image in this release"), one, 0),
        ("an absent board still showing a hash is caught",
         page("b" * 64, "Waveshare, kiss-signer-1-ws35.bin: " + "b" * 64), one, 1),
        ("a release board the page never baked is caught",
         page("", "Waveshare: no image in this release"), two, 2),
    ]:
        got = len(verify_page_problems(text, boards)) >= 1
        ok = got == bool(want)
        print("  %-52s %s (%s)" % (name, "ok" if ok else "FAILED", got))
        bad += not ok
        count += 1

    print("installer version selftest: %d cases, %d broken" % (count, bad))
    return 1 if bad else 0


def board_problems(release: dict, boards: list, version: str) -> list:
    """Every board's image against release.json and SHA256SUMS, and the
    top-level fields against the Guition's entry."""
    problems = []
    if not boards:
        return ["release.json lists no boards"]
    ids = [b.get("id") for b in boards]
    if len(set(ids)) != len(ids):
        problems.append(f"release.json lists a board twice: {ids}")
    if "guition" not in ids:
        problems.append("release.json has no Guition entry, and its top-level "
                        "fields are the Guition's")
    for key in ("manifest",):
        values = [b.get(key) for b in boards]
        if len(set(values)) != len(values):
            problems.append(f"two boards share a {key}: {values}")
    paths = [(b.get("browserFirmware") or {}).get("path") for b in boards]
    if len(set(paths)) != len(paths):
        problems.append(f"two boards share a firmware image: {paths}")

    if "boards" in release:
        guition = next((b for b in boards if b.get("id") == "guition"), {})
        if guition.get("browserFirmware") != release.get("browserFirmware"):
            problems.append("release.json's top-level browserFirmware is not the "
                            "Guition entry's, and older links read it as the Guition's")
        if guition.get("manifest") != "manifest.json":
            problems.append("the Guition's manifest is not manifest.json, the URL "
                            "every existing link to the installer uses")

    sums = {}
    sums_path = INSTALLER / "SHA256SUMS"
    if sums_path.is_file():
        for line in sums_path.read_text().splitlines():
            fields = line.split("  ", 1)
            if len(fields) == 2:
                sums[fields[1].strip()] = fields[0]

    for board in boards:
        bid = board.get("id")
        bf = board.get("browserFirmware") or {}
        path = bf.get("path")
        if not isinstance(path, str) or "//" in path or path.startswith("/"):
            problems.append(f"board {bid!r} has no relative browserFirmware.path")
            continue
        if not MANIFEST_RE.match(str(board.get("manifest"))):
            problems.append(f"board {bid!r} names manifest {board.get('manifest')!r}")
        image = INSTALLER / path
        if not image.is_file():
            problems.append(f"release.json names {path} for board {bid!r}, "
                            f"which does not exist")
            continue
        # The file the page hashes, against the numbers the page hashes it
        # against. A mismatch here is a page that refuses a genuine download.
        blob = image.read_bytes()
        digest = hashlib.sha256(blob).hexdigest()
        if len(blob) != bf.get("size"):
            problems.append(f"{path} is {len(blob)} bytes, release.json says {bf.get('size')}")
        if digest != bf.get("sha256"):
            problems.append(f"{path} hashes to {digest}, release.json says {bf.get('sha256')}")
        asset = pathlib.PurePosixPath(path).name
        if sums and sums.get(asset) != digest:
            problems.append(f"SHA256SUMS does not list {asset} with its hash")
    return problems


def manifest_problems(board: dict, version: str) -> list:
    """One board's manifest: VERSION, one build, one part, and that part the
    board's own image at the board's own offset."""
    problems = []
    name = board.get("manifest")
    if not MANIFEST_RE.match(str(name)):
        return problems            # reported by board_problems
    manifest_path = INSTALLER / name
    try:
        manifest = json.loads(manifest_path.read_text())
    except FileNotFoundError:
        return [f"{manifest_path.relative_to(ROOT)} is missing"]
    except json.JSONDecodeError as exc:
        return [f"{manifest_path.relative_to(ROOT)} is not valid JSON: {exc}"]

    # esp-web-tools shows this string in its own dialog, and the generator
    # writes "<version>-<git describe>", so match the prefix rather than
    # the whole value.
    manifest_version = manifest.get("version", "")
    if not manifest_version.startswith(version):
        problems.append(
            f"{name} version is {manifest_version!r}, "
            f"which does not start with {version!r}"
        )

    # Shape, not just version. esp-web-tools flashes EVERY part of the
    # matching build at its own offset. manifest.json IS hashed by
    # SHA256SUMS now, but the hash proves the bytes, not that the shape is
    # sane -- a signed manifest with an appended part is still arbitrary
    # bytes at an arbitrary offset. docs/app.js refuses this at flash
    # time; this refuses it at review time, where a JSON hunk with no
    # hash in it is easy to wave through.
    builds = manifest.get("builds")
    if not isinstance(builds, list) or len(builds) != 1:
        problems.append(
            f"{name} declares {len(builds) if isinstance(builds, list) else 'no'} "
            "builds, expected exactly 1"
        )
        return problems
    parts = builds[0].get("parts")
    if not isinstance(parts, list) or len(parts) != 1:
        problems.append(
            f"{name} declares {len(parts) if isinstance(parts, list) else 'no'} "
            "flash parts, expected exactly 1"
        )
    elif not isinstance(parts[0].get("path"), str) or "//" in parts[0]["path"]:
        problems.append(
            f"{name} part path {parts[0].get('path')!r} is not a "
            "relative path inside docs/installer"
        )
    else:
        # The page refuses a manifest that flashes anything but the board's
        # own image; so does this, before the page ever has to.
        bf = board.get("browserFirmware") or {}
        if bf and (parts[0]["path"] != bf.get("path") or
                   parts[0].get("offset") != bf.get("offset")):
            problems.append(
                f"{name} flashes {parts[0]['path']} at {parts[0].get('offset')}, "
                f"and release.json gives board {board.get('id')!r} "
                f"{bf.get('path')} at {bf.get('offset')}"
            )
    return problems


def main() -> int:
    if "--selftest" in sys.argv:
        return selftest()
    version = (ROOT / "VERSION").read_text().strip()
    problems = []

    release_path = INSTALLER / "release.json"
    release = None
    try:
        release = json.loads(release_path.read_text())
    except FileNotFoundError:
        problems.append(f"{release_path.relative_to(ROOT)} is missing")
    except json.JSONDecodeError as exc:
        problems.append(f"{release_path.relative_to(ROOT)} is not valid JSON: {exc}")

    boards = []
    if release is not None:
        if release.get("version") != version:
            problems.append(
                f"release.json version is {release.get('version')!r}, "
                f"VERSION is {version!r}"
            )
        # The firmware named here is the file the browser actually hashes and
        # flashes. A release.json pointing at a deleted binary is a page that
        # fails on load rather than at the button, which is harder to diagnose.
        firmware = (release.get("browserFirmware") or {}).get("path")
        if not firmware:
            problems.append("release.json has no browserFirmware.path")
        elif not (INSTALLER / firmware).is_file():
            problems.append(f"release.json names {firmware}, which does not exist")

        boards = release_boards(release)
        problems += board_problems(release, boards, version)
        # A board the release carries that the install page cannot select is an
        # image nobody can flash from the site.
        if INDEX.is_file():
            page = re.sub(r"<!--.*?-->", "", INDEX.read_text(), flags=re.DOTALL)
            for board in boards:
                if f'name="board" value="{board.get("id")}"' not in page:
                    problems.append(f"docs/index.html has no choice for board "
                                    f"{board.get('id')!r}, which release.json carries")

        # The commit the page shows a verifier, beside the firmware hash. It
        # has to be the string the device's own Settings line carries, or the
        # two disagree about one build and the verifier has no way to tell
        # which is lying.
        rev = release.get("commit")
        if not is_commit(rev):
            problems.append(
                f"release.json commit is {rev!r}, which is not a commit. "
                f"It must be the bare short hash the firmware carries, not a "
                f"git describe string naming an older tag."
            )

    # One manifest per board, each checked the same way the Guition's always
    # was. A release.json that could not be read still has manifest.json to
    # hold to VERSION.
    for board in boards or [{"id": "guition", "manifest": "manifest.json",
                             "browserFirmware": {}}]:
        problems += manifest_problems(board, version)

    # docs/verify-release.html bakes the expected hash, size and filename so it
    # works over file:// from the offline bundle with no network. A baked value
    # that drifts is worse than no page at all: it tells someone their genuine
    # download is corrupt, or worse, stays green for the previous release.
    verify_page = ROOT / "docs" / "verify-release.html"
    if verify_page.is_file() and release is not None:
        text = verify_page.read_text()
        problems += verify_page_problems(text, boards)
        if version not in text:
            problems.append(f"docs/verify-release.html does not name {version!r}")

    live = install_button_live()

    if problems:
        label = "FAIL" if live else "note"
        print(f"installer artifacts disagree with VERSION ({version}):\n")
        for problem in problems:
            print(f"  {label}  {problem}")
        print(
            "\nDo not hand edit the version strings: release.json carries the\n"
            "sha256 and size of a specific binary and docs/app.js verifies\n"
            "against them, so a version-only edit ships a page that fails its\n"
            "own hash check.\n\n"
            "  tools/make_web_release.sh      # from a release build\n\n"
            "regenerates all of them together. See docs/installer/SIGNING.md."
        )
        if live:
            print(
                "\nFAILED: docs/index.html still carries <esp-web-install-button>,\n"
                "so the site would hand a visitor this stale binary. Regenerate\n"
                "the artifacts, or pull the install card until you can."
            )
            return 1
        print(
            "\nPASSED anyway: the install card is pulled from docs/index.html,\n"
            "so nothing on the site can flash a device. Put the card back only\n"
            "after regenerating, or this check turns red."
        )
        return 0

    if not live:
        print(
            f"PASS: installer artifacts all describe {version}.\n"
            "The install card is currently pulled from docs/index.html, so the\n"
            "site is not offering them. Restoring it is now safe."
        )
        return 0

    print(f"PASS: installer artifacts all describe {version}, and the site offers them")
    return 0


if __name__ == "__main__":
    sys.exit(main())
