#!/usr/bin/env python3
"""Do the staged installer artifacts describe the release VERSION names?

docs/installer/ is what the browser installer writes to a device, and it is
generated by tools/make_web_release.sh from a real build. Nothing regenerates
it automatically, so it goes stale the moment VERSION moves and nothing notices
until someone flashes a device from the website and gets firmware the rest of
the documentation does not describe. That happened between beta6 and beta7: the
site served beta6 while the README, the changelog and every screenshot were
beta7, which is the storage release.

The version is hardcoded in four places. This checks all four agree with
VERSION, the same discipline already applied to screenshots by
tools/gen_docs_shots.py --check.

Hand editing the version strings does NOT fix a mismatch. The sha256 and size
in release.json describe a specific binary and docs/app.js verifies against
them, so editing the version alone produces a page that fails its own hash
check. The fix is to rerun tools/make_web_release.sh from a release build, or
to pull the install button until you can. See docs/installer/SIGNING.md.

What counts as a failure depends on whether the site is actually offering the
firmware. There are two consistent states and one broken one:

  * install card present, artifacts match VERSION   -> fine
  * install card pulled                             -> fine, nothing is offered
  * install card present, artifacts stale           -> BROKEN, this is the bug

So a stale artifact set is only fatal while docs/index.html still carries the
install button. With the button pulled it is reported and the check passes,
because no one can flash anything from the page. That keeps the tree mergeable
during the window where a release is staged, while making it impossible to put
the button back without regenerating first, which is the mistake worth
preventing.

Exit 0 when the site is consistent, 1 when it would offer a stale binary.
"""

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
INSTALLER = ROOT / "docs" / "installer"
BADGE = ROOT / "docs" / "readme" / "badge-version.svg"
INDEX = ROOT / "docs" / "index.html"


def install_button_live() -> bool:
    """Is the page actually offering to flash a device?

    The custom element is what does the flashing, so its presence in real
    markup is the signal. Commented-out markup does not count, which is how the
    button is parked while a release is staged.
    """
    if not INDEX.is_file():
        return False
    html = INDEX.read_text()
    html = re.sub(r"<!--.*?-->", "", html, flags=re.DOTALL)
    return "<esp-web-install-button" in html


def main() -> int:
    version = (ROOT / "VERSION").read_text().strip()
    problems = []

    release_path = INSTALLER / "release.json"
    release = None
    try:
        release = json.loads(release_path.read_text())
    except FileNotFoundError:
        problems.append(f"{release_path.relative_to(ROOT)} is missing")
    except json.JSONDecodeError as exc:
        problems.append(f"{release_path.relative_to(ROOT)} is not valid JSON: {exc}")

    if release is not None:
        if release.get("version") != version:
            problems.append(
                f"release.json version is {release.get('version')!r}, "
                f"VERSION is {version!r}"
            )
        # The firmware named here is the file the browser actually hashes and
        # flashes. A release.json pointing at a deleted binary is a page that
        # fails on load rather than at the button, which is harder to diagnose.
        firmware = (release.get("browserFirmware") or {}).get("path")
        if not firmware:
            problems.append("release.json has no browserFirmware.path")
        elif not (INSTALLER / firmware).is_file():
            problems.append(f"release.json names {firmware}, which does not exist")

    manifest_path = INSTALLER / "manifest.json"
    try:
        manifest = json.loads(manifest_path.read_text())
    except FileNotFoundError:
        problems.append(f"{manifest_path.relative_to(ROOT)} is missing")
    except json.JSONDecodeError as exc:
        problems.append(f"{manifest_path.relative_to(ROOT)} is not valid JSON: {exc}")
    else:
        # esp-web-tools shows this string in its own dialog, and the generator
        # writes "<version>-<git describe>", so match the prefix rather than
        # the whole value.
        manifest_version = manifest.get("version", "")
        if not manifest_version.startswith(version):
            problems.append(
                f"manifest.json version is {manifest_version!r}, "
                f"which does not start with {version!r}"
            )

        # Shape, not just version. esp-web-tools flashes EVERY part of the
        # matching build at its own offset. manifest.json IS hashed by
        # SHA256SUMS now, but the hash proves the bytes, not that the shape is
        # sane -- a signed manifest with an appended part is still arbitrary
        # bytes at an arbitrary offset. docs/app.js refuses this at flash
        # time; this refuses it at review time, where a JSON hunk with no
        # hash in it is easy to wave through.
        builds = manifest.get("builds")
        if not isinstance(builds, list) or len(builds) != 1:
            problems.append(
                f"manifest.json declares {len(builds) if isinstance(builds, list) else 'no'} "
                "builds, expected exactly 1"
            )
        else:
            parts = builds[0].get("parts")
            if not isinstance(parts, list) or len(parts) != 1:
                problems.append(
                    f"manifest.json declares {len(parts) if isinstance(parts, list) else 'no'} "
                    "flash parts, expected exactly 1"
                )
            elif not isinstance(parts[0].get("path"), str) or "//" in parts[0]["path"]:
                problems.append(
                    f"manifest.json part path {parts[0].get('path')!r} is not a "
                    "relative path inside docs/installer"
                )

    # docs/verify-release.html bakes the expected hash, size and filename so it
    # works over file:// from the offline bundle with no network. A baked value
    # that drifts is worse than no page at all: it tells someone their genuine
    # download is corrupt, or worse, stays green for the previous release.
    verify_page = ROOT / "docs" / "verify-release.html"
    if verify_page.is_file():
        text = verify_page.read_text()
        rel = json.loads((INSTALLER / "release.json").read_text())["browserFirmware"]
        for var, value in (
            ("EXPECT", f'"{rel["sha256"]}"'),
            ("EXPECT_SIZE", str(rel["size"])),
            ("EXPECT_NAME", f'"{pathlib.PurePosixPath(rel["path"]).name}"'),
        ):
            if f"var {var} = {value};" not in text:
                problems.append(
                    f"docs/verify-release.html {var} does not match release.json "
                    f"({value})"
                )
        if version not in text:
            problems.append(f"docs/verify-release.html does not name {version!r}")

    # The README badge is the fourth copy, and the only one a reader sees before
    # they download anything.
    if BADGE.is_file():
        text = re.sub(r"<[^>]+>", " ", BADGE.read_text())
        if version not in text:
            problems.append(
                f"docs/readme/badge-version.svg does not name {version!r}"
            )

    live = install_button_live()

    if problems:
        label = "FAIL" if live else "note"
        print(f"installer artifacts disagree with VERSION ({version}):\n")
        for problem in problems:
            print(f"  {label}  {problem}")
        print(
            "\nDo not hand edit the version strings: release.json carries the\n"
            "sha256 and size of a specific binary and docs/app.js verifies\n"
            "against them, so a version-only edit ships a page that fails its\n"
            "own hash check.\n\n"
            "  tools/make_web_release.sh      # from a release build\n\n"
            "regenerates all of them together. See docs/installer/SIGNING.md."
        )
        if live:
            print(
                "\nFAILED: docs/index.html still carries <esp-web-install-button>,\n"
                "so the site would hand a visitor this stale binary. Regenerate\n"
                "the artifacts, or pull the install card until you can."
            )
            return 1
        print(
            "\nPASSED anyway: the install card is pulled from docs/index.html,\n"
            "so nothing on the site can flash a device. Put the card back only\n"
            "after regenerating, or this check turns red."
        )
        return 0

    if not live:
        print(
            f"PASS: installer artifacts all describe {version}.\n"
            "The install card is currently pulled from docs/index.html, so the\n"
            "site is not offering them. Restoring it is now safe."
        )
        return 0

    print(f"PASS: installer artifacts all describe {version}, and the site offers them")
    return 0


if __name__ == "__main__":
    sys.exit(main())
