#!/usr/bin/env python3
"""Turn NIST's own SLH-DSA test vectors into the two headers this repo checks against.

    python3 tools/gen_pq_kat.py [--cache DIR]

Writes sim/pq_kat_vectors.h (the desktop suite) and main/pq_selftest_vectors.h
(the one case the device runs against its SHA accelerator).

Why NIST's and not ours. components/slhdsa is vendored, and a vendored library
checked against numbers the same library produced is a check that the copy did
not change -- not a check that it is right. These come from
usnistgov/ACVP-Server, which is the validation authority for FIPS 205, so they
are evidence of a different kind: the drop computes what the standard says.

The signature bodies are stored as SHA-256 of the expected signature, not the
7856 bytes themselves, everywhere except the device case -- which needs the real
signature because verifying one is the whole point of it. The messages are the
bulky part either way, so only short cases are taken.

The vectors are large (the sigGen file is 38 MB), so they are fetched on demand
and cached rather than committed. Nothing in CI needs this script: it writes
headers, and the headers are what is checked in.
"""

import argparse
import hashlib
import json
import os
import sys
import urllib.request

# Pinned, so a rerun writes the same headers.
ACVP_COMMIT = "975de31eb83d87039ec88934fdc47d8c312b892d"
ACVP_BASE = (
    "https://raw.githubusercontent.com/usnistgov/ACVP-Server/"
    + ACVP_COMMIT
    + "/gen-val/json-files/"
)
PARAM = "SLH-DSA-SHA2-128s"

# Which ACVP cases to carry, and why each one is here.
#
# Every one is deterministic (addrnd = NULL), because a hedged case cannot be
# reproduced without also feeding back the randomness, and the point is a known
# ANSWER. Chosen for short messages: the message is the only part of a case that
# is stored whole.
SIGGEN_PICKS = {
    # external interface, "pure", with a context string -- what kiss_pqsig uses.
    19: [
        160,  # 262 byte message, 158 byte context
        161,  # 1 byte message, 255 byte context: the maximum ctx FIPS 205 allows
        163,  # 2301 byte message, 54 byte context
    ],
    # internal interface, no context: the layer underneath, so a fault in the
    # domain separator above it cannot hide a fault in the tree below.
    31: [
        274,  # 1200 byte message
        276,  # 1 byte message
    ],
}
# The case the DEVICE verifies. Smallest message of the set, so the vector costs
# the signature and almost nothing else.
DEVICE_PICK = (19, 161)

HDR = """// GENERATED by tools/gen_pq_kat.py -- do not edit.
//
// SLH-DSA-SHA2-128s known answers from usnistgov/ACVP-Server
// @ {commit}
//
// NIST's numbers, not ours. components/slhdsa is a vendored library, and
// checking it against output it produced itself only proves the copy is intact.
#pragma once
#include <stdint.h>
#include <stddef.h>
"""


def fetch(name, cache):
    path = os.path.join(cache, name.replace("/", "_"))
    if not os.path.exists(path):
        os.makedirs(cache, exist_ok=True)
        sys.stderr.write("fetching %s ...\n" % name)
        urllib.request.urlretrieve(ACVP_BASE + name, path)
    return json.load(open(path))


def cbytes(h):
    """Hex string -> a C initializer, 12 bytes to a line."""
    b = bytes.fromhex(h)
    if not b:
        return "{0}"
    out, line = [], []
    for i, x in enumerate(b):
        line.append("0x%02X," % x)
        if len(line) == 12:
            out.append("    " + "".join(line))
            line = []
    if line:
        out.append("    " + "".join(line))
    return "{\n" + "\n".join(out) + "\n}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cache", default=os.path.expanduser("~/.cache/kiss-acvp"))
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed headers are not what this would write")
    args = ap.parse_args()

    # --check regenerates and compares rather than writing. It needs the ACVP
    # files, which are cached and never committed, so with no cache it reports
    # SKIP instead of failing: a machine that has never fetched them cannot
    # tell drift from absence, and a gate that fails for the wrong reason gets
    # ignored. The vectors come from a pinned upstream commit, so what this
    # actually catches is the pin or the case list moving without a regenerate.
    global CHECK, PENDING
    CHECK = args.check
    PENDING = {}
    if CHECK and not all(
        os.path.exists(os.path.join(args.cache, n.replace("/", "_")))
        for n in ("SLH-DSA-keyGen-FIPS205/internalProjection.json",
                  "SLH-DSA-sigGen-FIPS205/internalProjection.json")
    ):
        print("pq vectors: SKIP, no ACVP cache at %s "
              "(run tools/gen_pq_kat.py once to populate it)" % args.cache)
        raise SystemExit(0)

    kg = fetch("SLH-DSA-keyGen-FIPS205/internalProjection.json", args.cache)
    sg = fetch("SLH-DSA-sigGen-FIPS205/internalProjection.json", args.cache)

    kgroup = [g for g in kg["testGroups"] if g.get("parameterSet") == PARAM][0]
    sgroups = {g["tgId"]: g for g in sg["testGroups"]}

    # ---- sim/pq_kat_vectors.h
    o = [HDR.format(commit=ACVP_COMMIT)]
    o.append("\n// keyGen: (sk_seed, sk_prf, pk_seed) -> (sk, pk).")
    o.append("typedef struct { uint8_t sk_seed[16], sk_prf[16], pk_seed[16], sk[64], pk[32]; } pq_kat_keygen_t;")
    o.append("static const pq_kat_keygen_t PQ_KAT_KEYGEN[] = {")
    for t in kgroup["tests"]:
        o.append("  { .sk_seed = %s, .sk_prf = %s, .pk_seed = %s,"
                 % (cbytes(t["skSeed"]), cbytes(t["skPrf"]), cbytes(t["pkSeed"])))
        o.append("    .sk = %s, .pk = %s }," % (cbytes(t["sk"]), cbytes(t["pk"])))
    o.append("};\n")

    o.append("// sigGen, deterministic. sig_sha256 is SHA-256 of the 7856 byte")
    o.append("// signature ACVP expects; carrying the signatures whole would be 55 KB.")
    o.append("// external = the ctx form (slh_sign); !external = slh_sign_internal.")
    o.append("typedef struct {")
    o.append("  int tc_id, external;")
    o.append("  const uint8_t *msg; size_t msg_len;")
    o.append("  const uint8_t *ctx; size_t ctx_len;")
    o.append("  uint8_t sk[64], pk[32], sig_sha256[32];")
    o.append("} pq_kat_siggen_t;\n")

    body = []
    for tg, tcs in sorted(SIGGEN_PICKS.items()):
        g = sgroups[tg]
        assert g["parameterSet"] == PARAM and g["deterministic"], tg
        external = g["signatureInterface"] == "external"
        assert g.get("preHash") in ("pure", "none"), g.get("preHash")
        for tc in tcs:
            t = [x for x in g["tests"] if x["tcId"] == tc][0]
            msg, ctx = t["message"], t.get("context", "")
            o.append("static const uint8_t PQ_KAT_MSG_%d[] = %s;" % (tc, cbytes(msg)))
            if ctx:
                o.append("static const uint8_t PQ_KAT_CTX_%d[] = %s;" % (tc, cbytes(ctx)))
            digest = hashlib.sha256(bytes.fromhex(t["signature"])).hexdigest()
            body.append(
                "  { .tc_id = %d, .external = %d,\n"
                "    .msg = PQ_KAT_MSG_%d, .msg_len = %d,\n"
                "    .ctx = %s, .ctx_len = %d,\n"
                "    .sk = %s,\n    .pk = %s,\n    .sig_sha256 = %s },"
                % (tc, 1 if external else 0, tc, len(msg) // 2,
                   ("PQ_KAT_CTX_%d" % tc) if ctx else "NULL", len(ctx) // 2,
                   cbytes(t["sk"]), cbytes(t["pk"]), cbytes(digest))
            )
    o.append("")
    o.append("static const pq_kat_siggen_t PQ_KAT_SIGGEN[] = {")
    o += body
    o.append("};")
    write("sim/pq_kat_vectors.h", "\n".join(o) + "\n")

    # ---- main/pq_selftest_vectors.h
    tg, tc = DEVICE_PICK
    t = [x for x in sgroups[tg]["tests"] if x["tcId"] == tc][0]
    d = [HDR.format(commit=ACVP_COMMIT)]
    d.append("""
// ONE case, verified on the device at startup.
//
// The desktop suite cannot reach the code that matters here. The accelerator
// path in pq_hw_sha.c exists only when ESP_PLATFORM is defined, so every gate on
// a laptop tests the portable C and says nothing about the register mapping the
// device actually runs. Same argument as kiss_sign_selftest, which re-signs its
// vectors on the device because secp256k1 picks a different field backend there.
//
// Verify, not sign: 2199 compressions against 2.2 million, so this costs
// milliseconds at startup instead of seconds.
""".strip("\n"))
    # Explicit lengths, never sizeof. An empty field would still be a one byte
    # array here, and sizeof would call it a length of one -- which for a context
    # string is a different message and a signature that stops verifying.
    d.append("#define PQ_SELFTEST_TC_ID %d" % tc)
    for name, hexs in (("MSG", t["message"]), ("CTX", t.get("context", "")),
                       ("PK", t["pk"]), ("SIG", t["signature"])):
        d.append("#define PQ_SELFTEST_%s_LEN %d" % (name, len(hexs) // 2))
        d.append("static const uint8_t PQ_SELFTEST_%s[] = %s;" % (name, cbytes(hexs)))
    write("main/pq_selftest_vectors.h", "\n".join(d) + "\n")


CHECK = False
PENDING = {}


def write(path, text):
    if CHECK:
        PENDING[path] = text
        return
    open(path, "w", encoding="utf-8").write(text)
    sys.stderr.write("wrote %s (%d bytes)\n" % (path, len(text)))


def verify():
    """Compare what this run would have written against what is committed."""
    stale = []
    for path, text in PENDING.items():
        try:
            have = open(path, encoding="utf-8").read()
        except FileNotFoundError:
            stale.append("%s is missing" % path)
            continue
        if have != text:
            stale.append("%s does not match its generator" % path)
    if stale:
        for line in stale:
            sys.stderr.write("FAILED: %s\n" % line)
        sys.stderr.write("re-run: python3 tools/gen_pq_kat.py\n")
        raise SystemExit(1)
    print("pq vectors: %d header(s) match tools/gen_pq_kat.py at ACVP %s"
          % (len(PENDING), ACVP_COMMIT[:10]))


if __name__ == "__main__":
    main()
    if CHECK:
        verify()
