#!/usr/bin/env python3
"""Embed docs/verify.html as main/verify_page.c/.h for the SD card copy.

The page is the source of truth; the C array is generated, committed, and CI
diffs a regeneration against the committed copy so they cannot drift apart
(same contract as gen_i18n.py). Run after every edit to docs/verify.html:

    python3 tools/gen_verify_page.py

Hard checks before emitting, each a build-stopping property of the page:
  - its embedded wordlist is byte for word the libwally english.txt the
    firmware derives with (2048 words, same order),
  - it still names kiss-proof.bin and still parses #h= (the QR contract),
  - it stays under 100 KB (a pasted image or vendored library lands here
    long before it lands on the flash budget).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAGE = ROOT / "docs" / "verify.html"
WORDLIST = (ROOT / "components" / "libwally-core" / "upstream" / "src" /
            "data" / "wordlists" / "english.txt")
OUT_C = ROOT / "main" / "verify_page.c"
OUT_H = ROOT / "main" / "verify_page.h"

SIZE_CAP = 100 * 1024


def die(msg):
    print(f"gen_verify_page: {msg}", file=sys.stderr)
    sys.exit(1)


def main():
    data = PAGE.read_bytes()
    text = data.decode("utf-8")

    if len(data) > SIZE_CAP:
        die(f"docs/verify.html is {len(data)} bytes, cap is {SIZE_CAP}")
    for needle in ("#h=", "kiss-proof.bin", "KISS_CLAIM"):
        if needle not in text:
            die(f"docs/verify.html lost the string {needle!r}")

    # kiss_proof.c finds this placeholder by value and writes the run's hash
    # over it. Two of them, or none, and the card's copy stops self verifying
    # while every other check stays green.
    slot = "-" * 64
    if text.count(slot) != 1:
        die(f"expected exactly one 64 dash claim slot, found {text.count(slot)}")

    m = re.search(r'var WORDS = "([a-z ]+)"\.split\(" "\)', text)
    if not m:
        die("could not find the WORDS literal in docs/verify.html")
    page_words = m.group(1).split(" ")
    wally_words = WORDLIST.read_text("utf-8").split()
    if page_words != wally_words:
        die(f"page wordlist ({len(page_words)} words) differs from "
            f"{WORDLIST.relative_to(ROOT)} ({len(wally_words)} words)")

    banner = (f"// GENERATED by tools/gen_verify_page.py from docs/verify.html"
              f" - do not hand-edit\n")

    rows = []
    for i in range(0, len(data), 12):
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 12]) + ",")
    OUT_C.write_text(
        banner +
        '#include "verify_page.h"\n\n'
        "const uint8_t verify_page_html[] = {\n" +
        "\n".join(rows) +
        "\n};\n\n"
        "const size_t verify_page_html_len = sizeof verify_page_html;\n",
        "utf-8")

    OUT_H.write_text(
        banner +
        "// The offline audit checker, written to the card as WPROOF_PAGE_NAME\n"
        "// beside the frame it checks. See docs/specs/prove-it.md.\n"
        "#pragma once\n"
        "#include <stdint.h>\n"
        "#include <stddef.h>\n\n"
        "extern const uint8_t verify_page_html[];\n"
        "extern const size_t verify_page_html_len;\n",
        "utf-8")

    print(f"verify_page: {len(data)} bytes -> {OUT_C.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
