#!/usr/bin/env python3
"""Generate the wallet i18n tables from i18n/*.json.

Source of truth: i18n/en.json (key order there = enum order in i18n_keys.h).
Each locale file must carry exactly the same key set. Missing locale files
fall back to English with a warning (useful mid-development).

Emits (all marked GENERATED, never hand-edit):
  main/i18n_keys.h        enum STR_<KEY> ... STR_N
  main/i18n_tables.c      one const table per locale + the locale index
  tools/fonts/glyphs_*.txt  sorted non-ASCII codepoints per font class,
                            consumed by tools/fonts/gen_fonts.sh (M2)

Hard checks (exit 1): key-set mismatch, printf-specifier sequence mismatch
vs English (lv_vsnprintf has no positional args, so order is law), em/en
dashes (house style). Soft: warns when a translation is >40% longer than
the English (overflow risk on fixed 800x480 layouts).
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# enum order = firmware order = NVS "lang" values. APPEND ONLY: inserting a
# language re-numbers everything after it and breaks stored NVS settings.
# The native name mirrors main/i18n.c (picker labels); it is listed here so its
# glyphs are counted into the font subsets. Keep both in sync.
LOCALES = [
    # (file stem, C identifier, font class, native picker name)
    ("en", "en", "lat", "ENGLISH"),
    ("de", "de", "lat", "DEUTSCH"),
    ("es-MX", "es", "lat", "ESPAÑOL (MÉXICO)"),
    ("fr", "fr", "lat", "FRANÇAIS"),
    ("it", "it", "lat", "ITALIANO"),
    ("ja", "ja", "ja", "日本語"),
    ("ko", "ko", "ko", "한국어"),
    ("nl", "nl", "lat", "NEDERLANDS"),
    ("pl", "pl", "lat", "POLSKI"),
    ("pt-BR", "pt", "lat", "PORTUGUÊS (BRASIL)"),
    ("ru", "ru", "lat", "РУССКИЙ"),
    ("tr", "tr", "lat", "TÜRKÇE"),
    ("vi", "vi", "lat", "TIẾNG VIỆT"),
    ("zh-CN", "zh", "zh", "中文"),
    ("es-ES", "es_es", "lat", "ESPAÑOL (ESPAÑA)"),
    ("pt-PT", "pt_pt", "lat", "PORTUGUÊS (PORTUGAL)"),
    ("nb-NO", "nb", "lat", "NORSK BOKMÅL"),
    ("sv-SE", "sv", "lat", "SVENSKA"),
    ("da-DK", "da", "lat", "DANSK"),
    ("cs-CZ", "cs", "lat", "ČEŠTINA"),
    ("hr-HR", "hr", "lat", "HRVATSKI"),
]

# Must match LAT_RANGES in tools/fonts/gen_fonts.sh. A character outside the
# generated font is not a cosmetic problem: LVGL 9.5 hard-hangs rendering a
# label whose glyphs are all missing (line breaking never advances), so this
# check is a hard FAIL, on the sim and the device alike.
LAT_RANGES = [
    (0x20, 0x7E), (0xA0, 0xFF), (0x100, 0x17F), (0x1A0, 0x1B0),
    (0x1EA0, 0x1EF9), (0x400, 0x45F), (0x490, 0x491),
    (0x2018, 0x201D), (0x2022, 0x2022), (0x2026, 0x2026),
]


def lat_covered(ch):
    cp = ord(ch)
    return any(a <= cp <= b for a, b in LAT_RANGES)

SPEC_RE = re.compile(r"%(?:[-+ #0]*[0-9.]*(?:hh|h|ll|l|j|z|t|L)?[diuoxXeEfFgGaAcsp]|%)")

GEN_HDR = "// GENERATED by tools/gen_i18n.py - do not hand-edit\n"


def c_escape(s: str) -> str:
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        else:
            out.append(ch)  # raw UTF-8: LV_TXT_ENC_UTF8 on both builds
    return "".join(out)


def load(stem):
    p = ROOT / "i18n" / f"{stem}.json"
    if not p.exists():
        return None
    with open(p, encoding="utf-8") as f:
        return json.load(f)


def main():
    errors = []
    warnings = []

    en = load("en")
    if en is None:
        print("FATAL: i18n/en.json missing", file=sys.stderr)
        return 1
    keys = list(en.keys())
    en_specs = {k: SPEC_RE.findall(v) for k, v in en.items()}

    tables = {}
    for stem, ident, fc, _nat in LOCALES:
        data = load(stem) if stem != "en" else en
        if data is None:
            warnings.append(f"{stem}: no i18n/{stem}.json yet, falling back to English")
            data = en
        missing = [k for k in keys if k not in data]
        extra = [k for k in data if k not in en]
        if missing:
            errors.append(f"{stem}: missing keys: {', '.join(missing[:8])}"
                          + (" ..." if len(missing) > 8 else ""))
        if extra:
            errors.append(f"{stem}: unknown keys: {', '.join(extra[:8])}")
        for k in keys:
            v = data.get(k, en[k])
            v = v.replace(" ", " ")  # narrow nbsp -> nbsp (fr numbers)
            if "–" in v or "—" in v:
                errors.append(f"{stem}:{k}: em/en dash (house style: use , or :)")
            if SPEC_RE.findall(v) != en_specs[k]:
                errors.append(f"{stem}:{k}: printf specifiers differ from en "
                              f"({SPEC_RE.findall(v)} vs {en_specs[k]})")
            if stem != "en" and len(v) > max(12, len(en[k]) * 1.4):
                warnings.append(f"{stem}:{k}: {len(v)} chars vs {len(en[k])} en "
                                f"(+{len(v)*100//max(1,len(en[k]))-100}%), may overflow")
            if k.endswith("_FMT") and len(v.encode("utf-8")) + 16 > 190:
                errors.append(f"{stem}:{k}: formatted result can exceed the C "
                              f"buffers (~190 bytes incl. numbers); shorten it")
            if fc == "lat":
                bad = sorted({ch for ch in v if not lat_covered(ch) and ch != "\n"})
                if bad:
                    errors.append(f"{stem}:{k}: chars outside the lat font ranges "
                                  f"(would HANG LVGL): {' '.join(f'U+{ord(c):04X} {c}' for c in bad)}")
            data[k] = v
        tables[ident] = data

    for w in warnings:
        print(f"warn: {w}")
    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        return 1

    # ---- main/i18n_keys.h ----
    h = [GEN_HDR, "#pragma once\n\n", "enum {\n"]
    h += [f"    STR_{k},\n" for k in keys]
    h += ["    STR_N\n", "};\n"]
    (ROOT / "main" / "i18n_keys.h").write_text("".join(h), encoding="utf-8")

    # ---- main/i18n_tables.c ----
    c = [GEN_HDR, '#include "i18n.h"\n\n']
    for stem, ident, _fc, _nat in LOCALES:
        c.append(f"static const char *const tbl_{ident}[STR_N] = {{\n")
        for k in keys:
            c.append(f'    [STR_{k}] = "{c_escape(tables[ident][k])}",\n')
        c.append("};\n\n")
    c.append("const char *const *const i18n_tables[I18N_LANG_N] = {\n")
    for stem, ident, _fc, _nat in LOCALES:
        c.append(f"    tbl_{ident},\n")
    c.append("};\n")
    (ROOT / "main" / "i18n_tables.c").write_text("".join(c), encoding="utf-8")

    # ---- glyph inventories per font class (fed to lv_font_conv) ----
    # CJK subsets = exactly the characters that locale's strings + native
    # picker name use. Regenerate the fonts whenever these files change, or
    # new glyphs will be missing at runtime (= LVGL hang, see LAT_RANGES note).
    fontdir = ROOT / "tools" / "fonts"
    fontdir.mkdir(parents=True, exist_ok=True)
    classes = {}
    for stem, ident, fc, native in LOCALES:
        cs = classes.setdefault(fc, set())
        cs.update(ch for ch in native if ord(ch) > 0x7F)
        for k in keys:
            cs.update(ch for ch in tables[ident][k] if ord(ch) > 0x7F)
    for fc, cs in classes.items():
        txt = "".join(sorted(cs))
        (fontdir / f"glyphs_{fc}.txt").write_text(txt + "\n", encoding="utf-8")
        print(f"glyphs_{fc}.txt: {len(cs)} non-ASCII glyphs")

    # tile-title glyphs (H_TILE_*) for the 23px wallet-home fonts: keep these
    # subsets tiny, the 23px size exists only for the four home tiles
    for stem, ident, fc, _nat in LOCALES:
        if fc == "lat":
            continue
        cs = set()
        for k in keys:
            if k.startswith("H_TILE_"):
                cs.update(ch for ch in tables[ident][k] if ord(ch) > 0x7F)
        (fontdir / f"glyphs_tile_{fc}.txt").write_text("".join(sorted(cs)) + "\n",
                                                       encoding="utf-8")
        print(f"glyphs_tile_{fc}.txt: {len(cs)} glyphs")

    n_locales = len(LOCALES)
    print(f"OK: {len(keys)} keys x {n_locales} locales")
    return 0


if __name__ == "__main__":
    sys.exit(main())
