#!/usr/bin/env python3
"""Generate the wallet i18n tables from i18n/*.json.

Source of truth: i18n/en.json (key order there = enum order in i18n_keys.h).
Each locale file must carry exactly the same key set. Missing locale files
fall back to English with a warning (useful mid-development).

Emits (all marked GENERATED, never hand-edit):
  main/i18n_keys.h        enum STR_<KEY> ... STR_N
  main/i18n_tables.c      one const table per locale + the locale index
  tools/fonts/glyphs_*.txt  sorted non-ASCII codepoints per font class,
                            consumed by tools/fonts/gen_fonts.sh (M2)

Hard checks (exit 1): key-set mismatch, printf-specifier sequence mismatch
vs English (lv_vsnprintf has no positional args, so order is law), em/en
dashes (house style). Soft: warns when a translation is >40% longer than
the English (overflow risk on fixed 800x480 layouts).
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# THE locale manifest: adding a language = one i18n/<stem>.json + one row
# here (at the END). The generator emits the enum (i18n_keys.h), the metadata
# + picker-order tables (i18n_tables.c), and the font glyph lists from this
# list alone - nothing else to keep in sync.
#
# enum order = firmware order = NVS "lang" values. APPEND ONLY: inserting a
# language re-numbers everything after it and breaks stored NVS settings
# (FROZEN_NVS below hard-fails the build if a shipped position moves).
LOCALES = [
    # (file stem, C identifier, font class, native picker name)
    ("en", "en", "lat", "ENGLISH"),
    ("de", "de", "lat", "DEUTSCH"),
    ("es-MX", "es", "lat", "ESPAÑOL (MÉXICO)"),
    ("fr", "fr", "lat", "FRANÇAIS"),
    ("it", "it", "lat", "ITALIANO"),
    ("ja", "ja", "ja", "日本語"),
    ("ko", "ko", "ko", "한국어"),
    ("nl", "nl", "lat", "NEDERLANDS"),
    ("pl", "pl", "lat", "POLSKI"),
    ("pt-BR", "pt", "lat", "PORTUGUÊS (BRASIL)"),
    ("ru", "ru", "lat", "РУССКИЙ"),
    ("tr", "tr", "lat", "TÜRKÇE"),
    ("vi", "vi", "lat", "TIẾNG VIỆT"),
    ("zh-CN", "zh", "zh", "中文"),
    ("es-ES", "es_es", "lat", "ESPAÑOL (ESPAÑA)"),
    ("pt-PT", "pt_pt", "lat", "PORTUGUÊS (PORTUGAL)"),
    ("nb-NO", "nb", "lat", "NORSK BOKMÅL"),
    ("sv-SE", "sv", "lat", "SVENSKA"),
    ("da-DK", "da", "lat", "DANSK"),
    ("cs-CZ", "cs", "lat", "ČEŠTINA"),
    ("hr-HR", "hr", "lat", "HRVATSKI"),
]

# Every locale that has shipped in a release, frozen at its NVS value. A
# mismatch against LOCALES means someone reordered/inserted/removed a row -
# which would silently switch the language on every deployed device. New
# locales: append to LOCALES, ship, then freeze them here.
FROZEN_NVS = {
    "en": 0, "de": 1, "es-MX": 2, "fr": 3, "it": 4, "ja": 5, "ko": 6,
    "nl": 7, "pl": 8, "pt-BR": 9, "ru": 10, "tr": 11, "vi": 12, "zh-CN": 13,
    "es-ES": 14, "pt-PT": 15, "nb-NO": 16, "sv-SE": 17, "da-DK": 18,
    "cs-CZ": 19, "hr-HR": 20,
}

# Must match LAT_RANGES in tools/fonts/gen_fonts.sh. A character outside the
# generated font is not a cosmetic problem: LVGL 9.5 hard-hangs rendering a
# label whose glyphs are all missing (line breaking never advances), so this
# check is a hard FAIL, on the sim and the device alike.
LAT_RANGES = [
    (0x20, 0x7E), (0xA0, 0xFF), (0x100, 0x17F), (0x1A0, 0x1B0),
    (0x1EA0, 0x1EF9), (0x400, 0x45F), (0x490, 0x491),
    (0x2018, 0x201D), (0x2022, 0x2022), (0x2026, 0x2026),
]


def lat_covered(ch):
    cp = ord(ch)
    return any(a <= cp <= b for a, b in LAT_RANGES)

SPEC_RE = re.compile(r"%(?:[-+ #0]*[0-9.]*(?:hh|h|ll|l|j|z|t|L)?[diuoxXeEfFgGaAcsp]|%)")

GEN_HDR = "// GENERATED by tools/gen_i18n.py - do not hand-edit\n"


def c_escape(s: str) -> str:
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        else:
            out.append(ch)  # raw UTF-8: LV_TXT_ENC_UTF8 on both builds
    return "".join(out)


def load(stem):
    p = ROOT / "i18n" / f"{stem}.json"
    if not p.exists():
        return None
    with open(p, encoding="utf-8") as f:
        return json.load(f)


def pick_order():
    """Picker display order: alphabetical with variants adjacent (diacritics
    folded for sorting), Cyrillic after Latin, CJK last in enum order."""
    import unicodedata

    def key(i):
        native = LOCALES[i][3]
        cp = ord(native[0])
        bucket = 0 if cp < 0x370 else 1 if cp <= 0x4FF else 2
        folded = "".join(ch for ch in unicodedata.normalize("NFD", native)
                         if not unicodedata.combining(ch))
        return (bucket, folded if bucket < 2 else "", i)

    return sorted(range(len(LOCALES)), key=key)


# Keys that are legitimately the same in every language, so the untranslated
# check below must not flag them. Proper nouns and the Bitcoin address type
# names other wallets print in English too. Anything added here needs a reason
# on its line; "we did not get round to it" is not one.
UNTRANSLATED_OK = {
    "I_APP_DESKTOP",   # Sparrow, a product name
    "I_APP_MOBILE",    # BlueWallet, a product name
    "S_TY_LEGACY",     # Legacy / Nested SegWit / Native SegWit: the address type
    "S_TY_NESTED",     # names as every coordinator and the BIPs spell them, and
    "S_TY_NATIVE",     # the string a user matches against another wallet's UI
    "N_PARTS_FMT",     # %d/%d: digits and a slash, deliberately locale neutral
    "S_QR_PART_FMT",   # (SWEEP-03); ja/ko/tr/vi/zh already wrote "of" as "/"
    "W_WORD_N_FMT",    # %d/%d  %s_: same counter plus the typed-prefix echo
    # The coin path beside the dice one: same module, same judge, base 2. Born
    # under the English-only rule; English in the other twenty until the sweep.
    "W_METHOD_DICE_S", "W_METHOD_DICE_T", "W_COIN", "W_COIN_NOTE",
    "W_COIN_T", "W_COIN_S", "W_COIN_HEADS", "W_COIN_TAILS",
    "W_COIN_VERIFY_NOTE",
    # KEF backup strings: born under the English-only rule (translation is one
    # sweep AFTER the UI stops moving), so the other twenty carry the English
    # as a placeholder the sweep replaces. Remove these lines in that sweep.
    "L_KEF_TYPE_PROMPT",
    "L_KEF_PASS_NEW", "L_KEF_PASS_OPEN", "L_KEF_LOCKING", "L_KEF_UNLOCKING",
    "L_KEF_BAD", "L_KEF_FAIL", "L_KEF_WEAK_T", "L_KEF_WEAK_ACK",
    "I_ROW_KEF", "I_ROW_KEF_SUB", "I_KEF_WARN_S", "I_KEF_CHIP_QR",
    "I_KEF_W1_H", "I_KEF_W1_B", "I_KEF_W2_H", "I_KEF_W2_B",
    "I_KEF_MAKE_BTN", "I_KEF_SHOW_S", "I_KEF_SHOW_NOTE", "I_KEF_SD_BTN",
    "W_KEF_BAD_T", "W_KEF_BAD_S", "W_KEF_BAD_B",
    "W_KEF_SD_T", "W_KEF_SD_S", "W_KEF_SD_EMPTY", "W_KEF_SD_NONE_B",
    # What the envelope does NOT hold, shown only when a passphrase is in use.
    # Born under the English-only rule, like the block it sits in.
    "I_KEF_PP_H", "I_KEF_PP_B", "I_KEF_WARN_S_PP",
    # RECOVERY WORDS rebuilt on the section-tab chrome: two groups, PAPER and
    # ENCRYPTED, in place of two chips, a row wedged beside one of them and a
    # three paragraph body. Born under the English-only rule; English until the
    # sweep. Everything the page could reuse, it reuses -- these seven are the
    # tab labels and the row names that had no equivalent.
    "I_WTAB_PAPER", "I_WTAB_ENC", "I_WROW_SHOW", "I_WROW_SHOW_SUB",
    "I_WROW_CHECK", "I_WROW_KEF", "I_WROW_HOLDS",
    # Naming the artifacts rather than describing them: the encrypted backup
    # row prints the file it will write, and the SD screen stops borrowing the
    # firmware screen's caption for a byte pair. English until the sweep.
    "I_ROW_KEF_SUB_FMT", "G_SD_SPACE_CAP", "G_SD_ROW_WORDS_HERE",
    # The second refusal on the firmware screen: an image that passed the
    # secp256r1 check and was still refused, because its post quantum signature
    # was missing or wrong. It needed its own key rather than reusing
    # G_FW_FAIL_SIG_B, because a genuine KISS release from before the trailer
    # existed lands here, and telling that owner "the signature did not check
    # out" sends them hunting for a corrupt download. English until the sweep.
    "G_FW_FAIL_PQ_B",
    # KEYS and RECEIVE rebuilt on the section-tab chrome, borderless: a row is
    # a line with a rule under it, a tab is marked with brackets, a button is
    # an arrow with no box. Born under the English-only rule; English until the
    # sweep. Everything either screen could reuse, it reuses -- I_SEC_THIS_WALLET,
    # R_NEVER_HANDED, R_HANDED_ALREADY, R_SP_BTN and S_CMP_8 all ship already.
    # These eighteen are the ones with no equivalent.
    "K_FP_SUB", "K_CAP_PAIRING", "K_PAIR_SUB", "K_SP_SUB",
    "K_EXPL_COORD", "G_TEST_CHIP", "R_TAB_THIS", "R_ENLARGE", "R_PATH_CAP",
    "R_NEXT_ADDR", "R_LIST_COUNT", "R_TAB_SP", "R_ONE_EACH_SHORT", "R_USED_NOTE",
    "R_SP_ADDR_CAP", "R_SP_QR_SUB", "R_SP_EXPORT", "R_EXPL_SP",
    # RECEIVE's [ ? ] explainer, the last page to grow the mark. Born under
    # the English-only rule, like the block above.
    "R_HELP_HEAD", "R_HELP_BODY", "R_HELP_F1C", "R_HELP_F1V",
    "R_HELP_F2C", "R_HELP_F2V", "R_HELP_F3C", "R_HELP_F3V",
    # The erase card's paragraph, split into the claim PAIR the house rules
    # ask for -- one sentence stacking three claims was a wall of text and
    # overlapcheck said so. English until the sweep.
    "I_ERASE_H1", "I_ERASE_B1", "I_ERASE_H2", "I_ERASE_B2",
    # The THIS DEVICE row's sub-line. It used to carry two ASCII diagnostics
    # the screen behind it already prints, and never said the card was back
    # there. Born under the English-only rule; English until the sweep.
    "I_ROW_DEVICE_SUB",
    # The locked-backup scan, which replaced the seed-QR scan on both restore
    # doors. The old key's translations named a feature this signer no longer
    # has, so it was renamed rather than overwritten; English until the sweep.
    "W_SCAN_KEF_QR",
    # The method screen's first row. Same rule as the KEF block above: born
    # after the English-only rule, so the other twenty carry English until the
    # sweep. It needed its own keys because the row had been borrowing
    # W_CHOOSE_NEW / W_NEW_NOTE from the screen above it, where "NEW SEED
    # WORDS" against RESTORE is correct and must not move.
    "W_CHOOSE_MIX", "W_MIX_NOTE",
    # The checksum verdict, moved onto WRITE THESE DOWN where it matters.
    "W_WRITE_OK",
    # The locked-state explainer: reassurance for the five refusal renders.
    # Born under the English-only rule, like the KEF block above.
    "C_LOCKED_B", "C_LOCK_SOON",
    # Payee recognition on the verify screen. Born under the English-only rule,
    # like the KEF block above: the other twenty carry the English until the
    # sweep.
    "S_PAYEE_SEEN", "S_PAYEE_HELP",
    # The dice explainer, cut from four glossary terms to two claims. The old
    # key's translations described content that no longer exists, so it was
    # renamed rather than overwritten; English until the sweep.
    "W_DICE_HELP_B2",
    # The mix explainer, which gained a fourth source. Same reason as the line
    # above: the shape changed, so the key was renamed rather than overwritten
    # and the other twenty carry English until the sweep.
    "W_ENT_MIX_B2",
    # The audit chooser and the randomness audit. Born under the English-only
    # rule, like the KEF block above: the other twenty carry the English as a
    # placeholder the sweep replaces.
    "W_AUD_T", "W_AUD_S", "W_AUD_STAND",
    # What a coordinator says about which addresses the chain shows used, and
    # the Receive chip's third state for when none has said. Born under the
    # English-only rule, like the KEF block above: the other twenty carry the
    # English as a placeholder the sweep replaces.
    "R_USAGE_UNKNOWN", "R_CHAIN_UPTO_FMT", "R_CHAIN_CLEAN", "R_CHAIN_ASK",
    "R_UM_OTHER_KEYS", "R_UM_NO_CHANGE",
    # HOW YOUR KEYS WERE MADE: the record of which path produced this seed.
    # Born under the English-only rule, like the KEF block above.
    "W_MADE_T", "W_MADE_S", "W_MADE_CAP", "W_MADE_NONE", "W_MADE_ELSE",
    "W_MADE_NOREC",
    "W_RNG_T", "W_RNG_S", "W_RNG_SRC", "W_RNG_SRC_SUB",
    "W_RNG_ON", "W_RNG_OFF",
    "W_RNG_WHY1_H", "W_RNG_WHY1_B", "W_RNG_WHY2_H", "W_RNG_WHY2_B",
    "W_RNG_NOSRC_B", "W_RNG_GO", "W_RNG_AGAIN",
    "W_RNG_CHI_CAP", "W_RNG_RANGE_CAP",
    "W_RNG_EVEN", "W_RNG_TOOEVEN", "W_RNG_RETRY", "W_RNG_PASS_NOTE",
    # The third network and the chooser that names all three. Born under the
    # English-only rule, like the KEF block above: the other twenty carry the
    # English as a placeholder the sweep replaces.
    "I_NET_SIGNET", "R_ON_SIGNET",
    "I_NET_MAIN_NOTE", "I_NET_TEST_NOTE", "I_NET_SIGNET_NOTE",
    # The history switch: the Settings row, its chooser and the two truths the
    # ON row can tell. Born under the English-only rule, like the KEF block
    # above: the other twenty carry the English until the sweep.
    "I_ROW_HISTORY", "I_ROW_HISTORY_SUB", "I_SEC_HISTORY",
    "G_HIST_ON_BTN", "G_HIST_OFF_BTN",
    "G_HIST_ON_NOTE", "G_HIST_ON_NOTE_PLAIN", "G_HIST_OFF_NOTE",
    # CARD INFO behind the storage chooser: the pill, the fact rows, and the
    # no-card pair's right block. Same rule as the block above.
    "G_SD_INFO_PILL", "G_SD_ROW_FREE", "G_SD_ROW_PSBT", "G_SD_ROW_SIGNED_FMT",
    "G_SD_ROW_FW", "G_SD_ROW_KEF", "G_SD_ROW_WORDS_MISSING",
    "G_SD_ABOUT_H", "G_SD_ABOUT_B",
    # SETTINGS rebuilt as section tabs: the five groups' row labels, sub-lines
    # and explainers, the dropdown notes, the NO UNDO card, the address type
    # help card and the attention chip. Born under the English-only rule, like
    # the KEF block above: the other twenty carry the English until the sweep.
    "I_TAB_SIGNER", "I_TAB_SECURITY", "I_TAB_BACKUP", "I_TAB_DEVICE",
    "I_ROW_DENOM", "I_DENOM_SUB", "I_EXPL_SIGNER",
    "I_WAYSIN_SHORT", "I_HIST_SHORT", "I_ROW_AUDIT", "I_AUDIT_SUB",
    "I_EXPL_SECURITY",
    "I_PERSIST_DEAD_SUB", "I_PERSIST_DEAD_VAL",
    "I_STORE_FLASH_SUB", "I_STORE_FLASH_ENC_SUB", "I_STORE_SD_SUB",
    "I_STORE_AMN_SUB", "I_EXPL_BACKUP",
    "I_CARD_SUB",
    "I_ROW_LANG", "I_LANG_SUB", "I_THEME_SUB", "I_ROW_FW", "I_FW_SUB",
    "I_ROW_DEVICE", "I_DEVICE_T",
    "I_ERASE_B", "I_ERASE_BTN", "I_ERASE_CAP",
    "I_BIP_T", "I_BIP_CLOSE", "I_BIP_44_NOTE", "I_BIP_49_NOTE",
    "I_BIP_84_NOTE",
    "I_POP_CHIP", "I_POP_NOTHING", "I_POP_KEEP", "I_POP_ERASE",
    "I_ATTN_1", "I_ATTN_N_FMT",
    # FIRMWARE rebuilt on the same borderless chrome as KEYS and RECEIVE. The
    # screen's subject is now WHICH VERSION REPLACES WHICH, drawn once and
    # reused on the offer, the confirm and the verdict, so the lines under it
    # needed captions and the trade needed a lamp. Born under the English-only
    # rule; English until the sweep. Everything the chain could reuse, it
    # reuses -- every G_FW_* heading and body, S_FILES_MORE_FMT, C_BACK and
    # C_CANCEL all ship in 21 locales already. These eleven had no equivalent.
    "G_FW_ROW_FILE", "G_FW_ROW_SIG", "G_FW_SIG_PROMISE",
    "G_FW_NEWER_LAMP", "G_FW_OLDER_LAMP",
    "G_FW_WHERE_CAP", "G_FW_WHERE_SHORT", "G_FW_DOWN_SHORT",
    "G_FW_KEEP_HOLDING", "G_FW_WRITING_FMT", "G_FW_BACKLIGHT",
    # The screen system's first page: KEYS re-weighted so the fingerprint is
    # the headline (the hero, its caption and the line naming who to check it
    # against), the other facts opening plain-sentence definitions in place,
    # a standing statement in the band, and the [ ? ] explainer tab with its
    # one-time hint. Born under the English-only rule; English until the
    # sweep. C_CALLED_FMT and C_HELP_HINT are device-wide: every definition
    # ends on a CALLED: line and every page grows the same [ ? ].
    "K_FP_HERO_CAP", "K_FP_HERO_SUB", "K_STANDING",
    "K_NET_PLAIN_MAIN", "K_NET_PLAIN_TEST",
    "K_TYPE_PLAIN", "K_TYPE_TERM_FMT", "K_ADDR_PLAIN", "K_ADDR_TERM",
    "K_ADDR_SUB",
    "K_HELP_HEAD", "K_HELP_BODY",
    "K_HELP_F1C", "K_HELP_F1V", "K_HELP_F2C", "K_HELP_F2V",
    "K_HELP_F3C", "K_HELP_F3V",
    "C_HELP_HINT", "C_CALLED_FMT",
    # The gate (shape 4): the two captions every gate shares, the erase
    # gate's sentence, and the loss named by its fingerprint. Born under
    # the English-only rule; English until the sweep.
    "C_SURVIVES", "C_NOT_SURVIVES", "G_WIPE_CANT", "G_WIPE_GOES_FMT",
    "G_ERASED_NEXT", "G_NOERASE_NEXT",
    # The word grid (shape 3) and the WT_WARN gate now standing in front
    # of SHOW THE WORDS. Born under the English-only rule; English until
    # the sweep.
    "W_GRID_WARN", "W_SHOW_SENT", "W_SHOW_SURV", "W_SHOW_GOES",
    "W_HOLD_SHOW",
    "K_SPGATE_SENT", "K_SPGATE_SURV", "K_SPGATE_GOES",
    "K_COORD_NONE", "K_COORD_NONE_B",
    # The SETTINGS [ ? ] explainer. Born under the English-only rule;
    # English until the sweep.
    "G_HELP_HEAD", "G_HELP_BODY", "G_HELP_F1C", "G_HELP_F1V",
    "G_HELP_F2C", "G_HELP_F2V", "G_HELP_F3C", "G_HELP_F3V",
    # The storage gate and its outcomes. Born under the English-only
    # rule; English until the sweep.
    "G_STOGATE_SENT_SD", "G_STOGATE_SENT_AMN", "G_STOGATE_SENT_FLASH",
    "G_STOGATE_SURV", "G_STOGATE_GOES", "G_STOGATE_GOES_AMN",
    "G_STORAGE_OK_NEXT", "G_STORAGE_OK_NEXT_AMN",
    "G_STORAGE_CLEANUP_NEXT", "G_STORAGE_FAIL_NEXT",
}


def main():
    errors = []
    warnings = []

    for stem, want in FROZEN_NVS.items():
        stems = [l[0] for l in LOCALES]
        if stem not in stems or stems.index(stem) != want:
            errors.append(f"FROZEN_NVS: shipped locale {stem} must stay at "
                          f"enum value {want} (NVS 'lang' stores that byte); "
                          f"LOCALES is APPEND ONLY")

    en = load("en")
    if en is None:
        print("FATAL: i18n/en.json missing", file=sys.stderr)
        return 1
    keys = list(en.keys())
    en_specs = {k: SPEC_RE.findall(v) for k, v in en.items()}

    tables = {}
    for stem, ident, fc, _nat in LOCALES:
        data = load(stem) if stem != "en" else en
        if data is None:
            warnings.append(f"{stem}: no i18n/{stem}.json yet, falling back to English")
            data = en
        missing = [k for k in keys if k not in data]
        extra = [k for k in data if k not in en]
        if missing:
            errors.append(f"{stem}: missing keys: {', '.join(missing[:8])}"
                          + (" ..." if len(missing) > 8 else ""))
        if extra:
            errors.append(f"{stem}: unknown keys: {', '.join(extra[:8])}")
        for k in keys:
            v = data.get(k, en[k])
            v = v.replace(" ", " ")  # narrow nbsp -> nbsp (fr numbers)
            if "–" in v or "—" in v:
                errors.append(f"{stem}:{k}: em/en dash (house style: use , or :)")
            if SPEC_RE.findall(v) != en_specs[k]:
                errors.append(f"{stem}:{k}: printf specifiers differ from en "
                              f"({SPEC_RE.findall(v)} vs {en_specs[k]})")
            if v.count("\n") != en[k].count("\n"):
                errors.append(f"{stem}:{k}: {v.count(chr(10))} newlines vs "
                              f"{en[k].count(chr(10))} in en; a shape mismatch "
                              f"means the translation follows an older en "
                              f"(caught L_WARN_B stale in 20 locales)")
            if stem != "en" and len(v) > max(12, len(en[k]) * 1.4):
                warnings.append(f"{stem}:{k}: {len(v)} chars vs {len(en[k])} en "
                                f"(+{len(v)*100//max(1,len(en[k]))-100}%), may overflow")
            if k.endswith("_FMT") and len(v.encode("utf-8")) + 16 > 190:
                errors.append(f"{stem}:{k}: formatted result can exceed the C "
                              f"buffers (~190 bytes incl. numbers); shorten it")
            if fc == "lat":
                bad = sorted({ch for ch in v if not lat_covered(ch) and ch != "\n"})
                if bad:
                    errors.append(f"{stem}:{k}: chars outside the lat font ranges "
                                  f"(would HANG LVGL): {' '.join(f'U+{ord(c):04X} {c}' for c in bad)}")
            data[k] = v
        tables[ident] = data

    # ---- untranslated: byte identical to English in EVERY other locale ----
    #
    # A key that was never translated passes every other check in this file: it
    # exists in all 21 files, so the count reads "494 keys x 21 locales" and
    # looks finished. 62 keys were sitting like that, including the WALLET and
    # SETTINGS row labels every owner reads on every visit, and the whole seed
    # entropy flow. Nobody noticed because nothing asked.
    #
    # One locale matching English is normal and says nothing (Dutch "Network",
    # German "Wallet"). ALL TWENTY matching is not a coincidence, it is a string
    # that was added and never handed to the translators.
    en_ident = next(i for s, i, _f, _n in LOCALES if s == "en")
    for k in keys:
        if not en[k].strip() or k in UNTRANSLATED_OK:
            continue
        if all(tables[i].get(k) == en[k] for _s, i, _f, _n in LOCALES if i != en_ident):
            errors.append(f"{k}: identical to English in all {len(LOCALES)-1} other "
                          f"locales, so it was never translated: {en[k][:48]!r}. "
                          f"Translate it, or add it to UNTRANSLATED_OK with a reason")

    for w in warnings:
        print(f"warn: {w}")
    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        return 1

    # ---- main/i18n_keys.h ----
    h = [GEN_HDR, "#pragma once\n\n", "enum {\n"]
    h += [f"    STR_{k},\n" for k in keys]
    h += ["    STR_N\n", "};\n\n"]
    h += ["// Locale ids: order = i18n_tables[] = the persisted NVS 'lang'\n"
          "// value. APPEND ONLY (FROZEN_NVS in gen_i18n.py enforces it).\n",
          "enum {\n"]
    h += [f"    I18N_{ident.upper()}{' = 0' if i == 0 else ''},\n"
          for i, (_s, ident, _fc, _n) in enumerate(LOCALES)]
    h += ["    I18N_LANG_N\n", "};\n"]
    (ROOT / "main" / "i18n_keys.h").write_text("".join(h), encoding="utf-8")

    # ---- main/i18n_tables.c ----
    c = [GEN_HDR, '#include "i18n.h"\n\n']
    for stem, ident, _fc, _nat in LOCALES:
        c.append(f"static const char *const tbl_{ident}[STR_N] = {{\n")
        for k in keys:
            c.append(f'    [STR_{k}] = "{c_escape(tables[ident][k])}",\n')
        c.append("};\n\n")
    c.append("const char *const *const i18n_tables[I18N_LANG_N] = {\n")
    for stem, ident, _fc, _nat in LOCALES:
        c.append(f"    tbl_{ident},\n")
    c.append("};\n\n")

    # locale metadata (code / native picker name / font class) + the picker's
    # display order - all derived from LOCALES so the manifest is one place
    c.append("const i18n_lang_t i18n_langs[I18N_LANG_N] = {\n")
    for stem, ident, fc, native in LOCALES:
        c.append(f'    [I18N_{ident.upper()}] = {{"{stem}", '
                 f'"{c_escape(native)}", I18N_FC_{fc.upper()}}},\n')
    c.append("};\n\n")
    c.append("// alphabetical, es/pt variants adjacent, non-Latin scripts last\n")
    c.append("const uint8_t i18n_pick_order[I18N_LANG_N] = {\n")
    for i in pick_order():
        c.append(f"    I18N_{LOCALES[i][1].upper()},\n")
    c.append("};\n")
    (ROOT / "main" / "i18n_tables.c").write_text("".join(c), encoding="utf-8")

    # ---- glyph inventories per font class (fed to lv_font_conv) ----
    # CJK subsets = exactly the characters that locale's strings + native
    # picker name use. Regenerate the fonts whenever these files change, or
    # new glyphs will be missing at runtime (= LVGL hang, see LAT_RANGES note).
    fontdir = ROOT / "tools" / "fonts"
    fontdir.mkdir(parents=True, exist_ok=True)
    classes = {}
    for stem, ident, fc, native in LOCALES:
        cs = classes.setdefault(fc, set())
        cs.update(ch for ch in native if ord(ch) > 0x7F)
        for k in keys:
            cs.update(ch for ch in tables[ident][k] if ord(ch) > 0x7F)
    for fc, cs in classes.items():
        txt = "".join(sorted(cs))
        (fontdir / f"glyphs_{fc}.txt").write_text(txt + "\n", encoding="utf-8")
        print(f"glyphs_{fc}.txt: {len(cs)} non-ASCII glyphs")

    # tile-title glyphs (H_TILE_*) for the 23px wallet-home fonts: keep these
    # subsets tiny, the 23px size exists only for the four home tiles
    for stem, ident, fc, _nat in LOCALES:
        if fc == "lat":
            continue
        cs = set()
        for k in keys:
            if k.startswith("H_TILE_"):
                cs.update(ch for ch in tables[ident][k] if ord(ch) > 0x7F)
        (fontdir / f"glyphs_tile_{fc}.txt").write_text("".join(sorted(cs)) + "\n",
                                                       encoding="utf-8")
        print(f"glyphs_tile_{fc}.txt: {len(cs)} glyphs")

    n_locales = len(LOCALES)
    print(f"OK: {len(keys)} keys x {n_locales} locales")
    return 0


if __name__ == "__main__":
    sys.exit(main())
